var classes = [
    {
        "name": "Snicco\\Middleware\\MustMatchRoute\\MustMatchRoute",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "process",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Psr\\Http\\Server\\MiddlewareInterface",
            "Psr\\Http\\Message\\ResponseInterface",
            "Psr\\Http\\Message\\ServerRequestInterface",
            "Psr\\Http\\Server\\RequestHandlerInterface",
            "Snicco\\Component\\Psr7ErrorHandler\\HttpException"
        ],
        "parents": [],
        "implements": [
            "Psr\\Http\\Server\\MiddlewareInterface"
        ],
        "lcom": 1,
        "length": 13,
        "vocabulary": 8,
        "volume": 39,
        "difficulty": 3,
        "effort": 117,
        "level": 0.33,
        "bugs": 0.01,
        "time": 7,
        "intelligentContent": 13,
        "number_operators": 3,
        "number_operands": 10,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 12,
        "lloc": 12,
        "mi": 65.05,
        "mIwoC": 65.05,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.75,
        "relativeSystemComplexity": 9.75,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.75,
        "totalSystemComplexity": 9.75,
        "package": "Snicco\\Middleware\\MustMatchRoute\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    }
]