var classes = [
    {
        "name": "Snicco\\Component\\BetterWPDB\\Exception\\NoMatchingRowFound",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Snicco\\Component\\BetterWPDB\\Exception\\QueryException"
        ],
        "parents": [
            "Snicco\\Component\\BetterWPDB\\Exception\\QueryException"
        ],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Snicco\\Component\\BetterWPDB\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPDB\\Exception\\QueryException",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromMysqliE",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "RuntimeException",
            "mysqli_sql_exception"
        ],
        "parents": [
            "RuntimeException"
        ],
        "implements": [],
        "lcom": 2,
        "length": 50,
        "vocabulary": 23,
        "volume": 226.18,
        "difficulty": 8.09,
        "effort": 1830.63,
        "level": 0.12,
        "bugs": 0.08,
        "time": 102,
        "intelligentContent": 27.94,
        "number_operators": 13,
        "number_operands": 37,
        "number_operators_unique": 7,
        "number_operands_unique": 16,
        "cloc": 8,
        "loc": 31,
        "lloc": 23,
        "mi": 88.68,
        "mIwoC": 53.27,
        "commentWeight": 35.41,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.88,
        "relativeSystemComplexity": 10.88,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 3.75,
        "totalSystemComplexity": 21.75,
        "package": "Snicco\\Component\\BetterWPDB\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPDB\\MysqliFactory",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "fromWpdbConnection",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "mysqli",
            "ReflectionProperty"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 16,
        "vocabulary": 6,
        "volume": 41.36,
        "difficulty": 3,
        "effort": 124.08,
        "level": 0.33,
        "bugs": 0.01,
        "time": 7,
        "intelligentContent": 13.79,
        "number_operators": 4,
        "number_operands": 12,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 4,
        "loc": 17,
        "lloc": 13,
        "mi": 98.38,
        "mIwoC": 64.25,
        "commentWeight": 34.14,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 4.33,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 4.33,
        "package": "Snicco\\Component\\BetterWPDB\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPDB\\QueryInfo",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "replacePlaceholders",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 64,
        "vocabulary": 17,
        "volume": 261.6,
        "difficulty": 12,
        "effort": 3139.17,
        "level": 0.08,
        "bugs": 0.09,
        "time": 174,
        "intelligentContent": 21.8,
        "number_operators": 20,
        "number_operands": 44,
        "number_operators_unique": 6,
        "number_operands_unique": 11,
        "cloc": 29,
        "loc": 67,
        "lloc": 38,
        "mi": 90.66,
        "mIwoC": 48.07,
        "commentWeight": 42.58,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 4.5,
        "relativeSystemComplexity": 5.5,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 9,
        "totalSystemComplexity": 11,
        "package": "Snicco\\Component\\BetterWPDB\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPDB\\BetterWPDB",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromWpdb",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "preparedQuery",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "unprepared",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "transactional",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateByPrimary",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "select",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "selectAll",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "selectRow",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "selectValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "exists",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "selectLazy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "insert",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bulkInsert",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "runWithErrorHandling",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "queryOriginalSqlMode",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildInsertSql",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createPreparedStatement",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "escIdentifier",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "paramTypes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "log",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "convertBindings",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateTableName",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateProvidedColumnNames",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildWhereArray",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 27,
        "nbMethods": 27,
        "nbMethodsPrivate": 11,
        "nbMethodsPublic": 16,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 74,
        "ccn": 48,
        "ccnMethodMax": 6,
        "externals": [
            "mysqli",
            "",
            "Snicco\\Component\\BetterWPDB\\MysqliFactory",
            "mysqli_stmt",
            "Snicco\\Component\\BetterWPDB\\Exception\\QueryException",
            "Snicco\\Component\\BetterWPDB\\Exception\\QueryException",
            "Snicco\\Component\\BetterWPDB\\QueryInfo",
            "Snicco\\Component\\BetterWPDB\\Exception\\QueryException",
            "Snicco\\Component\\BetterWPDB\\QueryInfo",
            "Closure",
            "LogicException",
            "Snicco\\Component\\BetterWPDB\\Exception\\QueryException",
            "Snicco\\Component\\BetterWPDB\\QueryInfo",
            "Snicco\\Component\\BetterWPDB\\Exception\\QueryException",
            "Snicco\\Component\\BetterWPDB\\QueryInfo",
            "InvalidArgumentException",
            "mysqli_result",
            "Snicco\\Component\\BetterWPDB\\Exception\\NoMatchingRowFound",
            "Generator",
            "mysqli_stmt",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "Snicco\\Component\\BetterWPDB\\QueryInfo",
            "Closure",
            "RuntimeException",
            "RuntimeException",
            "RuntimeException",
            "mysqli_stmt",
            "Snicco\\Component\\BetterWPDB\\QueryInfo",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 658,
        "vocabulary": 105,
        "volume": 4417.97,
        "difficulty": 50.48,
        "effort": 223031.49,
        "level": 0.02,
        "bugs": 1.47,
        "time": 12391,
        "intelligentContent": 87.51,
        "number_operators": 170,
        "number_operands": 488,
        "number_operators_unique": 18,
        "number_operands_unique": 87,
        "cloc": 195,
        "loc": 543,
        "lloc": 348,
        "mi": 52.61,
        "mIwoC": 12.58,
        "commentWeight": 40.03,
        "kanDefect": 3.53,
        "relativeStructuralComplexity": 1024,
        "relativeDataComplexity": 0.87,
        "relativeSystemComplexity": 1024.87,
        "totalStructuralComplexity": 27648,
        "totalDataComplexity": 23.39,
        "totalSystemComplexity": 27671.39,
        "package": "Snicco\\Component\\BetterWPDB\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 13,
        "instability": 0.87,
        "violations": {}
    }
]