var classes = [
    {
        "name": "Snicco\\Component\\BetterWPDB\\MysqliFactory",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "fromWpdbConnection",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "mysqli",
            "ReflectionProperty"
        ],
        "parents": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 6,
        "volume": 38.77,
        "difficulty": 2.75,
        "effort": 106.63,
        "level": 0.36,
        "bugs": 0.01,
        "time": 6,
        "intelligentContent": 14.1,
        "number_operators": 4,
        "number_operands": 11,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 7,
        "loc": 20,
        "lloc": 13,
        "mi": 104.12,
        "mIwoC": 64.44,
        "commentWeight": 39.67,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "Snicco\\Component\\BetterWPDB\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPDB\\Exception\\QueryException",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromMysqliE",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "RuntimeException",
            "mysqli_sql_exception"
        ],
        "parents": [
            "RuntimeException"
        ],
        "lcom": 2,
        "length": 50,
        "vocabulary": 21,
        "volume": 219.62,
        "difficulty": 6.09,
        "effort": 1338.28,
        "level": 0.16,
        "bugs": 0.07,
        "time": 74,
        "intelligentContent": 36.04,
        "number_operators": 11,
        "number_operands": 39,
        "number_operators_unique": 5,
        "number_operands_unique": 16,
        "cloc": 8,
        "loc": 31,
        "lloc": 23,
        "mi": 88.77,
        "mIwoC": 53.36,
        "commentWeight": 35.41,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.88,
        "relativeSystemComplexity": 10.88,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 3.75,
        "totalSystemComplexity": 21.75,
        "package": "Snicco\\Component\\BetterWPDB\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPDB\\Exception\\NoMatchingRowFound",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Snicco\\Component\\BetterWPDB\\Exception\\QueryException"
        ],
        "parents": [
            "Snicco\\Component\\BetterWPDB\\Exception\\QueryException"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Snicco\\Component\\BetterWPDB\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPDB\\BetterWPDB",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromWpdb",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "preparedQuery",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "unprepared",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "transactional",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateByPrimary",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "select",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "selectAll",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "selectRow",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "selectValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "exists",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "selectLazy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "insert",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bulkInsert",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "runWithErrorHandling",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "queryOriginalSqlMode",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildInsertSql",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createPreparedStatement",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "escIdentifier",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "paramTypes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "log",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "convertBindings",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateTableName",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateProvidedColumnNames",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildWhereArray",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 27,
        "nbMethods": 27,
        "nbMethodsPrivate": 11,
        "nbMethodsPublic": 16,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 76,
        "ccn": 50,
        "ccnMethodMax": 7,
        "externals": [
            "mysqli",
            "",
            "Snicco\\Component\\BetterWPDB\\MysqliFactory",
            "mysqli_stmt",
            "Snicco\\Component\\BetterWPDB\\Exception\\QueryException",
            "Snicco\\Component\\BetterWPDB\\Exception\\QueryException",
            "Snicco\\Component\\BetterWPDB\\QueryInfo",
            "Snicco\\Component\\BetterWPDB\\Exception\\QueryException",
            "Snicco\\Component\\BetterWPDB\\QueryInfo",
            "Closure",
            "LogicException",
            "Snicco\\Component\\BetterWPDB\\Exception\\QueryException",
            "Snicco\\Component\\BetterWPDB\\QueryInfo",
            "Snicco\\Component\\BetterWPDB\\Exception\\QueryException",
            "Snicco\\Component\\BetterWPDB\\QueryInfo",
            "InvalidArgumentException",
            "mysqli_result",
            "Snicco\\Component\\BetterWPDB\\Exception\\NoMatchingRowFound",
            "Generator",
            "mysqli_stmt",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "Snicco\\Component\\BetterWPDB\\QueryInfo",
            "Closure",
            "RuntimeException",
            "RuntimeException",
            "RuntimeException",
            "mysqli_stmt",
            "Snicco\\Component\\BetterWPDB\\QueryInfo",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException"
        ],
        "parents": [],
        "lcom": 2,
        "length": 676,
        "vocabulary": 108,
        "volume": 4566.3,
        "difficulty": 47.54,
        "effort": 217100.15,
        "level": 0.02,
        "bugs": 1.52,
        "time": 12061,
        "intelligentContent": 96.04,
        "number_operators": 167,
        "number_operands": 509,
        "number_operators_unique": 17,
        "number_operands_unique": 91,
        "cloc": 188,
        "loc": 536,
        "lloc": 348,
        "mi": 51.91,
        "mIwoC": 12.21,
        "commentWeight": 39.7,
        "kanDefect": 3.53,
        "relativeStructuralComplexity": 1024,
        "relativeDataComplexity": 0.84,
        "relativeSystemComplexity": 1024.84,
        "totalStructuralComplexity": 27648,
        "totalDataComplexity": 22.58,
        "totalSystemComplexity": 27670.58,
        "package": "Snicco\\Component\\BetterWPDB\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 13,
        "instability": 0.93,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPDB\\QueryInfo",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "replacePlaceholders",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 63,
        "vocabulary": 19,
        "volume": 267.62,
        "difficulty": 10.15,
        "effort": 2717.37,
        "level": 0.1,
        "bugs": 0.09,
        "time": 151,
        "intelligentContent": 26.36,
        "number_operators": 19,
        "number_operands": 44,
        "number_operators_unique": 6,
        "number_operands_unique": 13,
        "cloc": 24,
        "loc": 60,
        "lloc": 36,
        "mi": 90.03,
        "mIwoC": 48.52,
        "commentWeight": 41.52,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 4,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 10,
        "package": "Snicco\\Component\\BetterWPDB\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    }
]