codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
    after_n_builds: 1

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.01%
        paths:
          - "src/Snicco/*"
        if_not_found: failure
        if_ci_failed: error

    # The difference is explained quite vague at https://docs.codecov.com/docs/commit-status#patch-status
    patch:
      default:
        target: auto
        threshold: 0.05%
        paths:
          - "src/Snicco/*"
        if_not_found: failure
        if_ci_failed: error

  precision: 3
  round: nearest
  range: "95...99"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,files"
  behavior: default
  require_changes: false
  require_head: yes
  require_base: yes
  after_n_builds: 2 # Only send notifications after 2 builds because we upload 2 times currently (1x PHPUnit / 1x Codeception)
