var classes = [
    {
        "name": "Snicco\\Component\\Templating\\ViewComposer\\ViewComposerCollection",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addComposer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "compose",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "matchingComposers",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 17,
        "ccn": 14,
        "ccnMethodMax": 6,
        "externals": [
            "Snicco\\Component\\Templating\\ViewComposer\\NewableInstanceViewComposerFactory",
            "Snicco\\Component\\Templating\\GlobalViewContext",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "Snicco\\Component\\Templating\\View\\View",
            "Snicco\\Component\\Templating\\View\\View",
            "Snicco\\Component\\Templating\\View\\View",
            "Snicco\\Component\\StrArr\\Str",
            "Snicco\\Component\\Templating\\ViewComposer\\ClosureViewComposer"
        ],
        "parents": [],
        "lcom": 1,
        "length": 90,
        "vocabulary": 19,
        "volume": 382.31,
        "difficulty": 6.56,
        "effort": 2508.93,
        "level": 0.15,
        "bugs": 0.13,
        "time": 139,
        "intelligentContent": 58.26,
        "number_operators": 20,
        "number_operands": 70,
        "number_operators_unique": 3,
        "number_operands_unique": 16,
        "cloc": 24,
        "loc": 79,
        "lloc": 55,
        "mi": 79.76,
        "mIwoC": 42.07,
        "commentWeight": 37.69,
        "kanDefect": 1.42,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 64.5,
        "totalStructuralComplexity": 256,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 258,
        "package": "Snicco\\Component\\Templating\\ViewComposer\\",
        "pageRank": 0,
        "afferentCoupling": 4,
        "efferentCoupling": 6,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Templating\\ViewComposer\\ClosureViewComposer",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "compose",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\Templating\\ViewComposer\\ViewComposer",
            "Closure",
            "Snicco\\Component\\Templating\\View\\View",
            "Snicco\\Component\\Templating\\View\\View"
        ],
        "parents": [],
        "lcom": 1,
        "length": 8,
        "vocabulary": 5,
        "volume": 18.58,
        "difficulty": 2,
        "effort": 37.15,
        "level": 0.5,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 9.29,
        "number_operators": 2,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 17,
        "loc": 30,
        "lloc": 13,
        "mi": 112.64,
        "mIwoC": 66.68,
        "commentWeight": 45.96,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "package": "Snicco\\Component\\Templating\\ViewComposer\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Templating\\ViewComposer\\NewableInstanceViewComposerFactory",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\Templating\\ViewComposer\\ViewComposerFactory",
            "Snicco\\Component\\Templating\\ViewComposer\\ViewComposer",
            "composer",
            "Snicco\\Component\\Templating\\Exception\\BadViewComposer"
        ],
        "parents": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 2,
        "effort": 51.7,
        "level": 0.5,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 12.92,
        "number_operators": 2,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 12,
        "lloc": 12,
        "mi": 66.3,
        "mIwoC": 66.3,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "Snicco\\Component\\Templating\\ViewComposer\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Templating\\OutputBuffer",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "start",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remove",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 2,
        "externals": [
            "RuntimeException",
            "RuntimeException",
            "RuntimeException"
        ],
        "parents": [],
        "lcom": 3,
        "length": 18,
        "vocabulary": 9,
        "volume": 57.06,
        "difficulty": 4,
        "effort": 228.23,
        "level": 0.25,
        "bugs": 0.02,
        "time": 13,
        "intelligentContent": 14.26,
        "number_operators": 8,
        "number_operands": 10,
        "number_operators_unique": 4,
        "number_operands_unique": 5,
        "cloc": 18,
        "loc": 44,
        "lloc": 26,
        "mi": 98.12,
        "mIwoC": 56.3,
        "commentWeight": 41.83,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "Snicco\\Component\\Templating\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Templating\\ViewEngine",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "make",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createFirstMatchingView",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 7,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Snicco\\Component\\Templating\\ViewFactory\\ViewFactory",
            "Snicco\\Component\\Templating\\View\\View",
            "Snicco\\Component\\Templating\\View\\View",
            "Snicco\\Component\\Templating\\Exception\\ViewNotFound"
        ],
        "parents": [],
        "lcom": 1,
        "length": 35,
        "vocabulary": 15,
        "volume": 136.74,
        "difficulty": 3.63,
        "effort": 495.69,
        "level": 0.28,
        "bugs": 0.05,
        "time": 28,
        "intelligentContent": 37.72,
        "number_operators": 6,
        "number_operands": 29,
        "number_operators_unique": 3,
        "number_operands_unique": 12,
        "cloc": 22,
        "loc": 52,
        "lloc": 30,
        "mi": 94.56,
        "mIwoC": 52.28,
        "commentWeight": 42.28,
        "kanDefect": 0.61,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.85,
        "relativeSystemComplexity": 16.85,
        "totalStructuralComplexity": 64,
        "totalDataComplexity": 3.4,
        "totalSystemComplexity": 67.4,
        "package": "Snicco\\Component\\Templating\\",
        "pageRank": 0,
        "afferentCoupling": 4,
        "efferentCoupling": 3,
        "instability": 0.43,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Templating\\Exception\\ViewNotFound",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "RuntimeException"
        ],
        "parents": [
            "RuntimeException"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Snicco\\Component\\Templating\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Templating\\Exception\\BadViewComposer",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "InvalidArgumentException"
        ],
        "parents": [
            "InvalidArgumentException"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Snicco\\Component\\Templating\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Templating\\Exception\\ViewCantBeRendered",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "fromPrevious",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "RuntimeException",
            "Snicco\\Component\\Templating\\Exception\\ViewCantBeRendered",
            "Throwable"
        ],
        "parents": [
            "RuntimeException"
        ],
        "lcom": 1,
        "length": 11,
        "vocabulary": 7,
        "volume": 30.88,
        "difficulty": 0.83,
        "effort": 25.73,
        "level": 1.2,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 37.06,
        "number_operators": 1,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 69.73,
        "mIwoC": 69.73,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 5,
        "package": "Snicco\\Component\\Templating\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 4,
        "efferentCoupling": 4,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Templating\\GlobalViewContext",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getArrayAccess",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "ArrayAccess",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\StrArr\\Arr",
            "BadMethodCallException",
            "BadMethodCallException",
            ""
        ],
        "parents": [],
        "lcom": 1,
        "length": 40,
        "vocabulary": 11,
        "volume": 138.38,
        "difficulty": 6,
        "effort": 830.26,
        "level": 0.17,
        "bugs": 0.05,
        "time": 46,
        "intelligentContent": 23.06,
        "number_operators": 8,
        "number_operands": 32,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 37,
        "loc": 80,
        "lloc": 43,
        "mi": 92.43,
        "mIwoC": 48.97,
        "commentWeight": 43.46,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.67,
        "relativeSystemComplexity": 5.67,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 17,
        "package": "Snicco\\Component\\Templating\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 4,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Templating\\ViewFactory\\ChildContent",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Closure",
            "Snicco\\Component\\Templating\\OutputBuffer",
            "Snicco\\Component\\Templating\\OutputBuffer"
        ],
        "parents": [],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 2,
        "effort": 24,
        "level": 0.5,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 6,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 3,
        "loc": 18,
        "lloc": 15,
        "mi": 96.21,
        "mIwoC": 66.65,
        "commentWeight": 29.56,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.75,
        "relativeSystemComplexity": 1.75,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 3.5,
        "package": "Snicco\\Component\\Templating\\ViewFactory\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Templating\\ViewFactory\\PHPViewFactory",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "make",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderPhpView",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "render",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "requireView",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handleViewException",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 4,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\Templating\\ViewFactory\\ViewFactory",
            "Snicco\\Component\\Templating\\ViewFactory\\PHPViewFinder",
            "Snicco\\Component\\Templating\\ViewComposer\\ViewComposerCollection",
            "Snicco\\Component\\Templating\\View\\PHPView",
            "Snicco\\Component\\Templating\\View\\PHPView",
            "Snicco\\Component\\Templating\\View\\PHPView",
            "Snicco\\Component\\Templating\\OutputBuffer",
            "Snicco\\Component\\Templating\\OutputBuffer",
            "Snicco\\Component\\Templating\\View\\PHPView",
            "Snicco\\Component\\Templating\\ViewFactory\\ChildContent",
            "Snicco\\Component\\Templating\\View\\View",
            "Throwable",
            "Snicco\\Component\\Templating\\View\\PHPView",
            "Snicco\\Component\\Templating\\OutputBuffer",
            "Snicco\\Component\\Templating\\Exception\\ViewCantBeRendered"
        ],
        "parents": [],
        "lcom": 1,
        "length": 64,
        "vocabulary": 16,
        "volume": 256,
        "difficulty": 19.44,
        "effort": 4977.78,
        "level": 0.05,
        "bugs": 0.09,
        "time": 277,
        "intelligentContent": 13.17,
        "number_operators": 14,
        "number_operands": 50,
        "number_operators_unique": 7,
        "number_operands_unique": 9,
        "cloc": 10,
        "loc": 60,
        "lloc": 50,
        "mi": 75.09,
        "mIwoC": 45.54,
        "commentWeight": 29.56,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.32,
        "relativeSystemComplexity": 169.32,
        "totalStructuralComplexity": 1014,
        "totalDataComplexity": 1.93,
        "totalSystemComplexity": 1015.93,
        "package": "Snicco\\Component\\Templating\\ViewFactory\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 9,
        "instability": 0.82,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Templating\\ViewFactory\\PHPViewFinder",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "filePath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "includeFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "normalize",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "normalizeViewName",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 5,
        "ccnMethodMax": 4,
        "externals": [
            "Snicco\\Component\\Templating\\Exception\\ViewNotFound"
        ],
        "parents": [],
        "lcom": 2,
        "length": 66,
        "vocabulary": 18,
        "volume": 275.22,
        "difficulty": 9.42,
        "effort": 2593.37,
        "level": 0.11,
        "bugs": 0.09,
        "time": 144,
        "intelligentContent": 29.21,
        "number_operators": 17,
        "number_operands": 49,
        "number_operators_unique": 5,
        "number_operands_unique": 13,
        "cloc": 20,
        "loc": 63,
        "lloc": 43,
        "mi": 84.92,
        "mIwoC": 46.61,
        "commentWeight": 38.31,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.73,
        "relativeSystemComplexity": 5.73,
        "totalStructuralComplexity": 20,
        "totalDataComplexity": 8.67,
        "totalSystemComplexity": 28.67,
        "package": "Snicco\\Component\\Templating\\ViewFactory\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Templating\\View\\PHPView",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "path",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "name",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "with",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "context",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parent",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parseParentView",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parseExtends",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 5,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 4,
        "nbMethodsSetters": 0,
        "wmc": 16,
        "ccn": 8,
        "ccnMethodMax": 6,
        "externals": [
            "Snicco\\Component\\Templating\\View\\View",
            "Snicco\\Component\\Templating\\ViewFactory\\PHPViewFactory",
            "Snicco\\Component\\Templating\\View\\View",
            "RuntimeException",
            "Snicco\\Component\\StrArr\\Str",
            "RuntimeException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 101,
        "vocabulary": 27,
        "volume": 480.24,
        "difficulty": 5.65,
        "effort": 2714.42,
        "level": 0.18,
        "bugs": 0.16,
        "time": 151,
        "intelligentContent": 84.97,
        "number_operators": 36,
        "number_operands": 65,
        "number_operators_unique": 4,
        "number_operands_unique": 23,
        "cloc": 31,
        "loc": 108,
        "lloc": 78,
        "mi": 75.77,
        "mIwoC": 38.87,
        "commentWeight": 36.9,
        "kanDefect": 0.64,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 2.09,
        "relativeSystemComplexity": 27.09,
        "totalStructuralComplexity": 225,
        "totalDataComplexity": 18.83,
        "totalSystemComplexity": 243.83,
        "package": "Snicco\\Component\\Templating\\View\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    }
]