# Inspired by https://github.com/symplify/symplify/blob/main/.github/workflows/split_monorepo.yaml
name: Split Monorepo

on:
  push:
    branches:
      - master
    tags:
      - '*'
  workflow_dispatch:

jobs:
  provide_packages_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - uses: "ramsey/composer-install@v1"

      # get package json list
      - id: package_json
        run: echo "::set-output name=matrix::$(php bin/monorepo_split_matrix)"

    # this step is needed, so the output gets to the next defined job
    outputs:
      matrix: ${{ steps.package_json.outputs.matrix }}

  split_monorepo:
    needs: provide_packages_json
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        packages: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Import GPG keys
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true
          git-config-global: true

      - name: Install composer dependencies
        uses: "ramsey/composer-install@v1"

      - name: Maybe Create GitHub Repo for package ${{ matrix.packages.full_name }}
        run: php bin/create-single-repo ${{ matrix.packages.relative_path }} --token=${{ secrets.ACCESS_TOKEN }}

      - name: Sleep 3s
        run: sleep 3s

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        # Uses an action in the root directory
        name: Monorepo Split of ${{ matrix.packages.full_name }}
        uses: symplify/github-action-monorepo-split@2.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: '${{ matrix.packages.relative_path }}'
          repository_organization: '${{ matrix.packages.vendor_name }}'
          repository_name: '${{ matrix.packages.name }}'
          user_name: "sniccowp-bot"
          user_email: "sniccowp-github@snicco.de"
          branch: "master"

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"

        name: Monorepo Tagged Split of ${{ matrix.packages.full_name }}
        uses: symplify/github-action-monorepo-split@2.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: '${{ matrix.packages.relative_path }}'
          repository_organization: '${{ matrix.packages.vendor_name }}'
          repository_name: '${{ matrix.packages.name }}'
          user_name: "sniccowp-bot"
          user_email: "sniccowp-github@snicco.de"
          branch: "master"

      - name: Sleep 3s
        run: sleep 3s

      - name: Maybe publish package ${{ matrix.packages.full_name }} at packagist.org
        run: php bin/push-to-packagist ${{ matrix.packages.relative_path }} --token=${{ secrets.PACKAGIST_API_TOKEN }} --u=${{ secrets.PACKAGIST_USERNAME }}