name: tests

on:
  push:
    branches: master
  pull_request:
  workflow_dispatch:

env:
  # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
  COMPOSER_ROOT_VERSION: "dev-master"

jobs:

  # These jobs are set in the branch protection rules for the master branch. They must run otherwise every PR
  # will be stuck at "Expected — Waiting for status to be reported ". For this reason we can not use GitHub's native path filters.
  # It's also not possible to run each job conditionally. The job must run. The only option is to run all steps conditionally.
  changes:
    name: Filter path for tests
    runs-on: ubuntu-20.04
    outputs:
      php: ${{ steps.filter.outputs.php }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Filter changed paths
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            php:
              - 'src/**/*.php'
              - 'tests/**/*.php'
              - 'phpunit.xml.dist'
              - 'codeception/*dist.yml'

  unit_tests:
    name: Unit Tests
    needs: changes
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: [ 7.4, 8.0, 8.1 ]
        dependencies: [ lowest, highest ]

    steps:
      - name: Checkout code
        if: ${{ needs.changes.outputs.php == 'true' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v2

      - name: Setup PHP [${{ matrix.php }}]
        if: ${{ needs.changes.outputs.php == 'true' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
          ini-values: error_reporting=E_ALL

      - name: Install composer dependencies
        if: ${{ needs.changes.outputs.php == 'true' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Run phpunit, testsuite unit
        if: ${{ needs.changes.outputs.php == 'true' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: composer phpunit:all

  wordpress_tests:
    name: WordPress Tests
    needs: changes
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1' ]
        wp: [ '5.8', '5.9' ]
        dependencies: [ lowest, highest ]

    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sniccowp_1
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=3s --health-timeout=3s --health-retries=10

      redis:
        image: redis:5.0
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Checkout code
        if: ${{ needs.changes.outputs.php == 'true' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v2

      - name: Setup PHP [${{ matrix.php }}]
        if: ${{ needs.changes.outputs.php == 'true' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, wp-cli
          coverage: none
          ini-values: error_reporting=E_ALL

      - name: Install composer dependencies
        if: ${{ needs.changes.outputs.php == 'true' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      # Config value must match the ones in env.testing.dist
      - name: Download WordPress [${{ matrix.wp }}]
        if: ${{ needs.changes.outputs.php == 'true' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: |
          mkdir wordpress && cd wordpress
          wp core download --force --skip-content --version=${{ matrix.wp }}
          wp config create --dbname="sniccowp_1" --dbuser="root" --dbpass="root" --dbhost="127.0.0.1" --dbprefix="wp_"
          wp core install --url="sniccowp.test" --title="SniccoWP" --admin_user="admin" --admin_password="admin" --admin_email="admin@sniccowp.com" --skip-email
          wp core update-db
          wp rewrite structure '/%postname%/'
          wp plugin install redis-cache
          wp plugin activate redis-cache
          wp redis enable
        working-directory: /tmp

      - name: Run WordPress tests with codeception
        if: ${{ needs.changes.outputs.php == 'true' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: composer codeception:all