var classes = [
    {
        "name": "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\Delegating",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "filter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\DisplayerFilter",
            "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\DisplayerFilter",
            "Psr\\Http\\Message\\RequestInterface",
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformation"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\DisplayerFilter"
        ],
        "lcom": 1,
        "length": 17,
        "vocabulary": 7,
        "volume": 47.73,
        "difficulty": 2.8,
        "effort": 133.63,
        "level": 0.36,
        "bugs": 0.02,
        "time": 7,
        "intelligentContent": 17.04,
        "number_operators": 3,
        "number_operands": 14,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 3,
        "loc": 19,
        "lloc": 16,
        "mi": 90.58,
        "mIwoC": 61.71,
        "commentWeight": 28.87,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 5,
        "package": "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\CanDisplay",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "filter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\DisplayerFilter",
            "Psr\\Http\\Message\\RequestInterface",
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformation"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\DisplayerFilter"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 5,
        "volume": 18.58,
        "difficulty": 0.88,
        "effort": 16.25,
        "level": 1.14,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 21.23,
        "number_operators": 1,
        "number_operands": 7,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 71.28,
        "mIwoC": 71.28,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 3,
        "package": "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\ContentType",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "filter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parse",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\DisplayerFilter",
            "Psr\\Http\\Message\\RequestInterface",
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformation"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\DisplayerFilter"
        ],
        "lcom": 1,
        "length": 34,
        "vocabulary": 14,
        "volume": 129.45,
        "difficulty": 3.41,
        "effort": 441.31,
        "level": 0.29,
        "bugs": 0.04,
        "time": 25,
        "intelligentContent": 37.97,
        "number_operators": 9,
        "number_operands": 25,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 5,
        "loc": 21,
        "lloc": 16,
        "mi": 92.84,
        "mIwoC": 58.54,
        "commentWeight": 34.3,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 10,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 20,
        "package": "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\Verbosity",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "filter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\DisplayerFilter",
            "Psr\\Http\\Message\\RequestInterface",
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformation"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\DisplayerFilter"
        ],
        "lcom": 1,
        "length": 13,
        "vocabulary": 9,
        "volume": 41.21,
        "difficulty": 2.5,
        "effort": 103.02,
        "level": 0.4,
        "bugs": 0.01,
        "time": 6,
        "intelligentContent": 16.48,
        "number_operators": 3,
        "number_operands": 10,
        "number_operators_unique": 3,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 13,
        "lloc": 13,
        "mi": 64.12,
        "mIwoC": 64.12,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 5,
        "package": "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Psr7ErrorHandler\\Information\\InformationProviderWithTransformation",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromDefaultData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createFor",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addMessage",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "transform",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getData",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 19,
        "ccn": 14,
        "ccnMethodMax": 6,
        "externals": [
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformationProvider",
            "Snicco\\Component\\Psr7ErrorHandler\\Identifier\\ExceptionIdentifier",
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionTransformer",
            "InvalidArgumentException",
            "Snicco\\Component\\Psr7ErrorHandler\\Identifier\\ExceptionIdentifier",
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionTransformer",
            "RuntimeException",
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformation",
            "Throwable",
            "Psr\\Http\\Message\\ServerRequestInterface",
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformation",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "Throwable",
            "Throwable",
            "Throwable",
            "Throwable"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformationProvider"
        ],
        "lcom": 2,
        "length": 147,
        "vocabulary": 37,
        "volume": 765.79,
        "difficulty": 15.31,
        "effort": 11724.5,
        "level": 0.07,
        "bugs": 0.26,
        "time": 651,
        "intelligentContent": 50.02,
        "number_operators": 36,
        "number_operands": 111,
        "number_operators_unique": 8,
        "number_operands_unique": 29,
        "cloc": 26,
        "loc": 97,
        "lloc": 71,
        "mi": 73.48,
        "mIwoC": 37.54,
        "commentWeight": 35.94,
        "kanDefect": 1.1,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.77,
        "relativeSystemComplexity": 49.77,
        "totalStructuralComplexity": 294,
        "totalDataComplexity": 4.63,
        "totalSystemComplexity": 298.63,
        "package": "Snicco\\Component\\Psr7ErrorHandler\\Information\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 8,
        "instability": 0.89,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformation",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "statusCode",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "identifier",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "safeTitle",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "originalException",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "transformedException",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "safeDetails",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "serverRequest",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 7,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Throwable",
            "Throwable",
            "Psr\\Http\\Message\\ServerRequestInterface",
            "Throwable",
            "Throwable",
            "Psr\\Http\\Message\\ServerRequestInterface"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 42,
        "vocabulary": 10,
        "volume": 139.52,
        "difficulty": 3.5,
        "effort": 488.32,
        "level": 0.29,
        "bugs": 0.05,
        "time": 27,
        "intelligentContent": 39.86,
        "number_operators": 14,
        "number_operands": 28,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 49,
        "lloc": 49,
        "mi": 47.98,
        "mIwoC": 47.98,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 7.88,
        "relativeSystemComplexity": 7.88,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 63,
        "totalSystemComplexity": 63,
        "package": "Snicco\\Component\\Psr7ErrorHandler\\Information\\",
        "pageRank": 0,
        "afferentCoupling": 16,
        "efferentCoupling": 2,
        "instability": 0.11,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Psr7ErrorHandler\\HttpException",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromPrevious",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "headers",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "statusCode",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "RuntimeException",
            "Throwable",
            "Throwable"
        ],
        "parents": [
            "RuntimeException"
        ],
        "implements": [],
        "lcom": 2,
        "length": 29,
        "vocabulary": 10,
        "volume": 96.34,
        "difficulty": 3,
        "effort": 289.01,
        "level": 0.33,
        "bugs": 0.03,
        "time": 16,
        "intelligentContent": 32.11,
        "number_operators": 5,
        "number_operands": 24,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 12,
        "loc": 36,
        "lloc": 24,
        "mi": 94.86,
        "mIwoC": 55.87,
        "commentWeight": 38.99,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 10.25,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 41,
        "package": "Snicco\\Component\\Psr7ErrorHandler\\",
        "pageRank": 0,
        "afferentCoupling": 7,
        "efferentCoupling": 2,
        "instability": 0.22,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Psr7ErrorHandler\\TestErrorHandler",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\Psr7ErrorHandler\\HttpErrorHandler",
            "Psr\\Http\\Message\\ResponseInterface",
            "Throwable",
            "Psr\\Http\\Message\\ServerRequestInterface"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Psr7ErrorHandler\\HttpErrorHandler"
        ],
        "lcom": 1,
        "length": 3,
        "vocabulary": 2,
        "volume": 3,
        "difficulty": 0,
        "effort": 0,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 3,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 76.82,
        "mIwoC": 76.82,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "Snicco\\Component\\Psr7ErrorHandler\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 4,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Psr7ErrorHandler\\ProductionErrorHandler",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logException",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createResponse",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findBestDisplayer",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handleDisplayError",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withHttpHeaders",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 5,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 8,
        "ccnMethodMax": 4,
        "externals": [
            "Snicco\\Component\\Psr7ErrorHandler\\HttpErrorHandler",
            "Psr\\Http\\Message\\ResponseFactoryInterface",
            "Snicco\\Component\\Psr7ErrorHandler\\Log\\RequestAwareLogger",
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformationProvider",
            "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\DisplayerFilter",
            "Snicco\\Component\\Psr7ErrorHandler\\Displayer\\ExceptionDisplayer",
            "Psr\\Http\\Message\\ResponseInterface",
            "Throwable",
            "Psr\\Http\\Message\\ServerRequestInterface",
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformation",
            "Psr\\Http\\Message\\ResponseInterface",
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformation",
            "Snicco\\Component\\Psr7ErrorHandler\\Displayer\\ExceptionDisplayer",
            "Snicco\\Component\\Psr7ErrorHandler\\Displayer\\ExceptionDisplayer",
            "Psr\\Http\\Message\\ServerRequestInterface",
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformation",
            "Snicco\\Component\\Psr7ErrorHandler\\DisplayerFilter\\ContentType",
            "Snicco\\Component\\Psr7ErrorHandler\\Displayer\\FallbackHtmlDisplayer",
            "Snicco\\Component\\Psr7ErrorHandler\\Displayer\\FallbackJsonDisplayer",
            "Psr\\Http\\Message\\ResponseInterface",
            "Throwable",
            "Psr\\Http\\Message\\ServerRequestInterface",
            "Psr\\Http\\Message\\ResponseInterface",
            "Throwable",
            "Psr\\Http\\Message\\ResponseInterface"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Psr7ErrorHandler\\HttpErrorHandler"
        ],
        "lcom": 1,
        "length": 138,
        "vocabulary": 29,
        "volume": 670.4,
        "difficulty": 11.15,
        "effort": 7472.18,
        "level": 0.09,
        "bugs": 0.22,
        "time": 415,
        "intelligentContent": 60.15,
        "number_operators": 31,
        "number_operands": 107,
        "number_operators_unique": 5,
        "number_operands_unique": 24,
        "cloc": 6,
        "loc": 81,
        "lloc": 75,
        "mi": 58.69,
        "mIwoC": 38.23,
        "commentWeight": 20.46,
        "kanDefect": 0.66,
        "relativeStructuralComplexity": 256,
        "relativeDataComplexity": 0.66,
        "relativeSystemComplexity": 256.66,
        "totalStructuralComplexity": 1792,
        "totalDataComplexity": 4.65,
        "totalSystemComplexity": 1796.65,
        "package": "Snicco\\Component\\Psr7ErrorHandler\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 13,
        "instability": 0.93,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Psr7ErrorHandler\\Identifier\\SplHashIdentifier",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "identify",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\Psr7ErrorHandler\\Identifier\\ExceptionIdentifier",
            "Throwable"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Psr7ErrorHandler\\Identifier\\ExceptionIdentifier"
        ],
        "lcom": 1,
        "length": 3,
        "vocabulary": 2,
        "volume": 3,
        "difficulty": 1,
        "effort": 3,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 3,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 76.82,
        "mIwoC": 76.82,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "Snicco\\Component\\Psr7ErrorHandler\\Identifier\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Psr7ErrorHandler\\Displayer\\FallbackHtmlDisplayer",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "display",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "supportedContentType",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isVerbose",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "canDisplay",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\Psr7ErrorHandler\\Displayer\\ExceptionDisplayer",
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformation",
            "RuntimeException",
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformation"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Psr7ErrorHandler\\Displayer\\ExceptionDisplayer"
        ],
        "lcom": 4,
        "length": 39,
        "vocabulary": 18,
        "volume": 162.63,
        "difficulty": 5.19,
        "effort": 844.41,
        "level": 0.19,
        "bugs": 0.05,
        "time": 47,
        "intelligentContent": 31.32,
        "number_operators": 12,
        "number_operands": 27,
        "number_operators_unique": 5,
        "number_operands_unique": 13,
        "cloc": 2,
        "loc": 29,
        "lloc": 27,
        "mi": 72.81,
        "mIwoC": 53.02,
        "commentWeight": 19.79,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.9,
        "relativeSystemComplexity": 16.9,
        "totalStructuralComplexity": 64,
        "totalDataComplexity": 3.6,
        "totalSystemComplexity": 67.6,
        "package": "Snicco\\Component\\Psr7ErrorHandler\\Displayer\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Psr7ErrorHandler\\Displayer\\FallbackJsonDisplayer",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "display",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "supportedContentType",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isVerbose",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "canDisplay",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\Psr7ErrorHandler\\Displayer\\ExceptionDisplayer",
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformation",
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformation"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Psr7ErrorHandler\\Displayer\\ExceptionDisplayer"
        ],
        "lcom": 4,
        "length": 14,
        "vocabulary": 7,
        "volume": 39.3,
        "difficulty": 0.83,
        "effort": 32.75,
        "level": 1.2,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 47.16,
        "number_operators": 4,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 20,
        "lloc": 20,
        "mi": 60.32,
        "mIwoC": 60.32,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.13,
        "relativeSystemComplexity": 10.13,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 4.5,
        "totalSystemComplexity": 40.5,
        "package": "Snicco\\Component\\Psr7ErrorHandler\\Displayer\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Psr7ErrorHandler\\Log\\RequestAwareLogger",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "log",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addLogLevel",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "determineLogLevel",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 7,
        "ccnMethodMax": 5,
        "externals": [
            "Psr\\Log\\LoggerInterface",
            "Snicco\\Component\\Psr7ErrorHandler\\Log\\RequestLogContext",
            "Snicco\\Component\\Psr7ErrorHandler\\Information\\ExceptionInformation",
            "Throwable"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 64,
        "vocabulary": 20,
        "volume": 276.6,
        "difficulty": 6.38,
        "effort": 1763.35,
        "level": 0.16,
        "bugs": 0.09,
        "time": 98,
        "intelligentContent": 43.39,
        "number_operators": 13,
        "number_operands": 51,
        "number_operators_unique": 4,
        "number_operands_unique": 16,
        "cloc": 12,
        "loc": 53,
        "lloc": 41,
        "mi": 80.39,
        "mIwoC": 46.78,
        "commentWeight": 33.61,
        "kanDefect": 0.98,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.44,
        "relativeSystemComplexity": 64.44,
        "totalStructuralComplexity": 256,
        "totalDataComplexity": 1.78,
        "totalSystemComplexity": 257.78,
        "package": "Snicco\\Component\\Psr7ErrorHandler\\Log\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 4,
        "instability": 0.67,
        "violations": {}
    }
]