var classes = [
    {
        "name": "Snicco\\Middleware\\WPAuth\\Authenticate",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "process",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Psr\\Http\\Server\\MiddlewareInterface",
            "Snicco\\Component\\BetterWPAPI\\BetterWPAPI",
            "Snicco\\Component\\BetterWPAPI\\BetterWPAPI",
            "Psr\\Http\\Message\\ResponseInterface",
            "Psr\\Http\\Message\\ServerRequestInterface",
            "Psr\\Http\\Server\\RequestHandlerInterface",
            "Snicco\\Component\\Psr7ErrorHandler\\HttpException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 16,
        "vocabulary": 10,
        "volume": 53.15,
        "difficulty": 2.79,
        "effort": 148.06,
        "level": 0.36,
        "bugs": 0.02,
        "time": 8,
        "intelligentContent": 19.08,
        "number_operators": 3,
        "number_operands": 13,
        "number_operators_unique": 3,
        "number_operands_unique": 7,
        "cloc": 0,
        "loc": 17,
        "lloc": 17,
        "mi": 60.67,
        "mIwoC": 60.67,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.36,
        "relativeSystemComplexity": 36.36,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0.71,
        "totalSystemComplexity": 72.71,
        "package": "Snicco\\Middleware\\WPAuth\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    }
]