var classes = [
    {
        "name": "Snicco\\Component\\WPObjectCachePsr16\\Exception\\BadTtl",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "InvalidArgumentException",
            "Psr\\SimpleCache\\InvalidArgumentException"
        ],
        "parents": [
            "InvalidArgumentException"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Snicco\\Component\\WPObjectCachePsr16\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\WPObjectCachePsr16\\Exception\\BadKey",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "InvalidArgumentException",
            "Psr\\SimpleCache\\InvalidArgumentException"
        ],
        "parents": [
            "InvalidArgumentException"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Snicco\\Component\\WPObjectCachePsr16\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\WPObjectCachePsr16\\WPCacheAPI",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "cacheGetMultiple",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cacheFlush",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\BetterWPAPI\\BetterWPAPI"
        ],
        "parents": [
            "Snicco\\Component\\BetterWPAPI\\BetterWPAPI"
        ],
        "lcom": 2,
        "length": 12,
        "vocabulary": 7,
        "volume": 33.69,
        "difficulty": 1.8,
        "effort": 60.64,
        "level": 0.56,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 18.72,
        "number_operators": 3,
        "number_operands": 9,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 11,
        "loc": 24,
        "lloc": 13,
        "mi": 108.21,
        "mIwoC": 64.87,
        "commentWeight": 43.34,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 7,
        "package": "Snicco\\Component\\WPObjectCachePsr16\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\WPObjectCachePsr16\\WPObjectCachePsr16",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMultiple",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setMultiple",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "set",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteMultiple",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validatedKey",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validatedUnserialize",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 11,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 41,
        "ccn": 31,
        "ccnMethodMax": 7,
        "externals": [
            "Psr\\SimpleCache\\CacheInterface",
            "Snicco\\Component\\WPObjectCachePsr16\\WPCacheAPI",
            "Snicco\\Component\\WPObjectCachePsr16\\Exception\\BadKey",
            "Snicco\\Component\\WPObjectCachePsr16\\Exception\\BadKey",
            "DateTimeImmutable",
            "Snicco\\Component\\WPObjectCachePsr16\\Exception\\BadTtl",
            "Snicco\\Component\\WPObjectCachePsr16\\Exception\\BadKey",
            "Snicco\\Component\\WPObjectCachePsr16\\Exception\\BadKey",
            "Snicco\\Component\\WPObjectCachePsr16\\Exception\\BadKey",
            "Snicco\\Component\\WPObjectCachePsr16\\Exception\\BadKey",
            "RuntimeException",
            "RuntimeException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 261,
        "vocabulary": 43,
        "volume": 1416.26,
        "difficulty": 21.14,
        "effort": 29943.68,
        "level": 0.05,
        "bugs": 0.47,
        "time": 1664,
        "intelligentContent": 66.99,
        "number_operators": 76,
        "number_operands": 185,
        "number_operators_unique": 8,
        "number_operands_unique": 35,
        "cloc": 54,
        "loc": 202,
        "lloc": 148,
        "mi": 62.33,
        "mIwoC": 26.42,
        "commentWeight": 35.9,
        "kanDefect": 2.63,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 1.11,
        "relativeSystemComplexity": 145.11,
        "totalStructuralComplexity": 1584,
        "totalDataComplexity": 12.23,
        "totalSystemComplexity": 1596.23,
        "package": "Snicco\\Component\\WPObjectCachePsr16\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    }
]