var classes = [
    {
        "name": "Snicco\\Middleware\\Payload\\Payload",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parse",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "shouldParseRequest",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 5,
        "ccnMethodMax": 4,
        "externals": [
            "Snicco\\Component\\HttpRouting\\Middleware\\Middleware",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert",
            "Psr\\Http\\Message\\ResponseInterface",
            "Snicco\\Component\\HttpRouting\\Http\\Psr7\\Request",
            "Snicco\\Component\\HttpRouting\\Middleware\\NextMiddleware",
            "Psr\\Http\\Message\\StreamInterface",
            "Snicco\\Component\\HttpRouting\\Http\\Psr7\\Request"
        ],
        "parents": [
            "Snicco\\Component\\HttpRouting\\Middleware\\Middleware"
        ],
        "implements": [],
        "lcom": 1,
        "length": 49,
        "vocabulary": 18,
        "volume": 204.33,
        "difficulty": 5.14,
        "effort": 1050.82,
        "level": 0.19,
        "bugs": 0.07,
        "time": 58,
        "intelligentContent": 39.73,
        "number_operators": 13,
        "number_operands": 36,
        "number_operators_unique": 4,
        "number_operands_unique": 14,
        "cloc": 15,
        "loc": 50,
        "lloc": 35,
        "mi": 86.98,
        "mIwoC": 49.47,
        "commentWeight": 37.52,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.81,
        "relativeSystemComplexity": 49.81,
        "totalStructuralComplexity": 196,
        "totalDataComplexity": 3.25,
        "totalSystemComplexity": 199.25,
        "package": "Snicco\\Middleware\\Payload\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 6,
        "instability": 0.86,
        "violations": {}
    },
    {
        "name": "Snicco\\Middleware\\Payload\\JsonToArray",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parse",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "Snicco\\Middleware\\Payload\\Payload",
            "Psr\\Http\\Message\\StreamInterface",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "Snicco\\Middleware\\Payload\\CantParseRequestBody"
        ],
        "parents": [
            "Snicco\\Middleware\\Payload\\Payload"
        ],
        "implements": [],
        "lcom": 2,
        "length": 31,
        "vocabulary": 17,
        "volume": 126.71,
        "difficulty": 4.58,
        "effort": 580.76,
        "level": 0.22,
        "bugs": 0.04,
        "time": 32,
        "intelligentContent": 27.65,
        "number_operators": 9,
        "number_operands": 22,
        "number_operators_unique": 5,
        "number_operands_unique": 12,
        "cloc": 4,
        "loc": 33,
        "lloc": 29,
        "mi": 78.25,
        "mIwoC": 52.57,
        "commentWeight": 25.68,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.83,
        "relativeSystemComplexity": 4.83,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1.67,
        "totalSystemComplexity": 9.67,
        "package": "Snicco\\Middleware\\Payload\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Snicco\\Middleware\\Payload\\CantParseRequestBody",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\Psr7ErrorHandler\\HttpException",
            "Throwable"
        ],
        "parents": [
            "Snicco\\Component\\Psr7ErrorHandler\\HttpException"
        ],
        "implements": [],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 0,
        "effort": 0,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 6,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 72.61,
        "mIwoC": 72.61,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "Snicco\\Middleware\\Payload\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    }
]