var classes = [
    {
        "name": "Snicco\\Component\\BetterWPMail\\Mailer",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "send",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fireSendingEvent",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "prepareAndValidate",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "determineSender",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "mergeRecipientsFromHeaders",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fireSentEvent",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 5,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 28,
        "ccn": 22,
        "ccnMethodMax": 16,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\Transport\\WPMailTransport",
            "Snicco\\Component\\BetterWPMail\\Renderer\\FilesystemRenderer",
            "Snicco\\Component\\BetterWPMail\\Renderer\\AggregateRenderer",
            "Snicco\\Component\\BetterWPMail\\Event\\NullEvents",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailDefaults",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\Event\\SendingEmail",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
            "Snicco\\Component\\BetterWPMail\\Event\\SendingEmail",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "LogicException",
            "LogicException",
            "LogicException",
            "LogicException",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "LogicException",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
            "Snicco\\Component\\BetterWPMail\\Event\\EmailWasSent"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 200,
        "vocabulary": 38,
        "volume": 1049.59,
        "difficulty": 20.79,
        "effort": 21824.14,
        "level": 0.05,
        "bugs": 0.35,
        "time": 1212,
        "intelligentContent": 50.48,
        "number_operators": 66,
        "number_operands": 134,
        "number_operators_unique": 9,
        "number_operands_unique": 29,
        "cloc": 7,
        "loc": 104,
        "lloc": 97,
        "mi": 52.11,
        "mIwoC": 32.55,
        "commentWeight": 19.56,
        "kanDefect": 1.29,
        "relativeStructuralComplexity": 1156,
        "relativeDataComplexity": 0.22,
        "relativeSystemComplexity": 1156.22,
        "totalStructuralComplexity": 8092,
        "totalDataComplexity": 1.51,
        "totalSystemComplexity": 8093.51,
        "package": "Snicco\\Component\\BetterWPMail\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 12,
        "instability": 0.92,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Exception\\CouldNotRenderMailContent",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "RuntimeException"
        ],
        "parents": [
            "RuntimeException"
        ],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Snicco\\Component\\BetterWPMail\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Exception\\CantSendEmailWithWPMail",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "becauseWPMailRaisedErrors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDebugData",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "RuntimeException",
            "Snicco\\Component\\BetterWPMail\\Exception\\CantSendEmail",
            "Throwable",
            "Snicco\\Component\\BetterWPMail\\Exception\\CantSendEmailWithWPMail",
            "WP_Error"
        ],
        "parents": [
            "RuntimeException"
        ],
        "implements": [
            "Snicco\\Component\\BetterWPMail\\Exception\\CantSendEmail"
        ],
        "lcom": 2,
        "length": 30,
        "vocabulary": 15,
        "volume": 117.21,
        "difficulty": 1.85,
        "effort": 216.38,
        "level": 0.54,
        "bugs": 0.04,
        "time": 12,
        "intelligentContent": 63.49,
        "number_operators": 6,
        "number_operands": 24,
        "number_operators_unique": 2,
        "number_operands_unique": 13,
        "cloc": 1,
        "loc": 22,
        "lloc": 21,
        "mi": 72.75,
        "mIwoC": 56.54,
        "commentWeight": 16.22,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.11,
        "relativeSystemComplexity": 5.11,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 3.33,
        "totalSystemComplexity": 15.33,
        "package": "Snicco\\Component\\BetterWPMail\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 6,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\WPMailAPI",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "mail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "adminEmail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "siteName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "siteUrl",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\BetterWPAPI\\BetterWPAPI"
        ],
        "parents": [
            "Snicco\\Component\\BetterWPAPI\\BetterWPAPI"
        ],
        "implements": [],
        "lcom": 3,
        "length": 21,
        "vocabulary": 12,
        "volume": 75.28,
        "difficulty": 0.77,
        "effort": 58.17,
        "level": 1.29,
        "bugs": 0.03,
        "time": 3,
        "intelligentContent": 97.43,
        "number_operators": 4,
        "number_operands": 17,
        "number_operators_unique": 1,
        "number_operands_unique": 11,
        "cloc": 18,
        "loc": 38,
        "lloc": 20,
        "mi": 102.11,
        "mIwoC": 58.34,
        "commentWeight": 43.77,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.63,
        "relativeSystemComplexity": 3.63,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 10.5,
        "totalSystemComplexity": 14.5,
        "package": "Snicco\\Component\\BetterWPMail\\",
        "pageRank": 0,
        "afferentCoupling": 4,
        "efferentCoupling": 1,
        "instability": 0.2,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Event\\SendingEmail",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email"
        ],
        "parents": [],
        "implements": [],
        "lcom": 0,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 0.75,
        "effort": 4.75,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 8.45,
        "number_operators": 1,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 14,
        "lloc": 9,
        "mi": 113.39,
        "mIwoC": 73.43,
        "commentWeight": 39.96,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "Snicco\\Component\\BetterWPMail\\Event\\",
        "pageRank": 0,
        "afferentCoupling": 5,
        "efferentCoupling": 1,
        "instability": 0.17,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Event\\NullEvents",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "fireSending",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fireSent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\Event\\MailEvents",
            "Snicco\\Component\\BetterWPMail\\Event\\SendingEmail",
            "Snicco\\Component\\BetterWPMail\\Event\\EmailWasSent"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\BetterWPMail\\Event\\MailEvents"
        ],
        "lcom": 2,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 2,
        "loc": 12,
        "lloc": 10,
        "mi": 105.5,
        "mIwoC": 75.94,
        "commentWeight": 29.56,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "Snicco\\Component\\BetterWPMail\\Event\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 3,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Event\\MailEventsUsingWPHooks",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fireSending",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fireSent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\Event\\MailEvents",
            "Snicco\\Component\\BetterWPMail\\WPMailAPI",
            "Snicco\\Component\\BetterWPMail\\WPMailAPI",
            "Snicco\\Component\\BetterWPMail\\Event\\SendingEmail",
            "Snicco\\Component\\BetterWPMail\\Event\\EmailWasSent"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\BetterWPMail\\Event\\MailEvents"
        ],
        "lcom": 1,
        "length": 11,
        "vocabulary": 5,
        "volume": 25.54,
        "difficulty": 1.25,
        "effort": 31.93,
        "level": 0.8,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 20.43,
        "number_operators": 1,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 17,
        "lloc": 17,
        "mi": 63.04,
        "mIwoC": 63.04,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 4.5,
        "package": "Snicco\\Component\\BetterWPMail\\Event\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 4,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Event\\EmailWasSent",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "email",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "envelope",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 12,
        "vocabulary": 5,
        "volume": 27.86,
        "difficulty": 2.67,
        "effort": 74.3,
        "level": 0.38,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 10.45,
        "number_operators": 4,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 19,
        "lloc": 19,
        "mi": 61.85,
        "mIwoC": 61.85,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.67,
        "relativeSystemComplexity": 2.67,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 8,
        "package": "Snicco\\Component\\BetterWPMail\\Event\\",
        "pageRank": 0,
        "afferentCoupling": 5,
        "efferentCoupling": 2,
        "instability": 0.29,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\ValueObject\\MailDefaults",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromWordPressSettings",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFrom",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getReplyTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 6,
        "ccnMethodMax": 5,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\WPMailAPI",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailDefaults",
            "Snicco\\Component\\BetterWPMail\\WPMailAPI",
            "Snicco\\Component\\BetterWPMail\\WPMailAPI",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailDefaults",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 51,
        "vocabulary": 11,
        "volume": 176.43,
        "difficulty": 4.44,
        "effort": 784.14,
        "level": 0.23,
        "bugs": 0.06,
        "time": 44,
        "intelligentContent": 39.7,
        "number_operators": 11,
        "number_operands": 40,
        "number_operators_unique": 2,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 31,
        "lloc": 31,
        "mi": 50.93,
        "mIwoC": 50.93,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.06,
        "relativeSystemComplexity": 10.06,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 4.25,
        "totalSystemComplexity": 40.25,
        "package": "Snicco\\Component\\BetterWPMail\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 4,
        "efferentCoupling": 4,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sender",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "recipients",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 22,
        "vocabulary": 11,
        "volume": 76.11,
        "difficulty": 4.29,
        "effort": 326.17,
        "level": 0.23,
        "bugs": 0.03,
        "time": 18,
        "intelligentContent": 17.76,
        "number_operators": 7,
        "number_operands": 15,
        "number_operators_unique": 4,
        "number_operands_unique": 7,
        "cloc": 3,
        "loc": 28,
        "lloc": 25,
        "mi": 80.21,
        "mIwoC": 55.93,
        "commentWeight": 24.28,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 2.33,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 7,
        "package": "Snicco\\Component\\BetterWPMail\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 5,
        "efferentCoupling": 3,
        "instability": 0.38,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "merge",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "count",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getIterator",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addAddress",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 5,
        "ccnMethodMax": 2,
        "externals": [
            "Countable",
            "IteratorAggregate",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "ArrayIterator",
            "ArrayIterator",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox"
        ],
        "parents": [],
        "implements": [
            "Countable",
            "IteratorAggregate"
        ],
        "lcom": 2,
        "length": 42,
        "vocabulary": 9,
        "volume": 133.14,
        "difficulty": 7.75,
        "effort": 1031.81,
        "level": 0.13,
        "bugs": 0.04,
        "time": 57,
        "intelligentContent": 17.18,
        "number_operators": 11,
        "number_operands": 31,
        "number_operators_unique": 3,
        "number_operands_unique": 6,
        "cloc": 18,
        "loc": 62,
        "lloc": 44,
        "mi": 85.66,
        "mIwoC": 48.6,
        "commentWeight": 37.06,
        "kanDefect": 0.68,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.31,
        "relativeSystemComplexity": 17.31,
        "totalStructuralComplexity": 112,
        "totalDataComplexity": 9.2,
        "totalSystemComplexity": 121.2,
        "package": "Snicco\\Component\\BetterWPMail\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 7,
        "efferentCoupling": 6,
        "instability": 0.46,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "name",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "address",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isEmailValid",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 5,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 19,
        "ccn": 15,
        "ccnMethodMax": 11,
        "externals": [
            "InvalidArgumentException",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "LogicException"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 113,
        "vocabulary": 24,
        "volume": 518.1,
        "difficulty": 12.67,
        "effort": 6562.61,
        "level": 0.08,
        "bugs": 0.17,
        "time": 365,
        "intelligentContent": 40.9,
        "number_operators": 37,
        "number_operands": 76,
        "number_operators_unique": 6,
        "number_operands_unique": 18,
        "cloc": 16,
        "loc": 93,
        "lloc": 77,
        "mi": 67.79,
        "mIwoC": 37.82,
        "commentWeight": 29.96,
        "kanDefect": 0.99,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 4.24,
        "relativeSystemComplexity": 8.24,
        "totalStructuralComplexity": 28,
        "totalDataComplexity": 29.67,
        "totalSystemComplexity": 57.67,
        "package": "Snicco\\Component\\BetterWPMail\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 8,
        "efferentCoupling": 4,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\ValueObject\\Attachment",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__destruct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromPath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bodyAsString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "name",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "contentType",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isInline",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "disposition",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "encoding",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cid",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 8,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "wmc": 22,
        "ccn": 15,
        "ccnMethodMax": 5,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Attachment",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Attachment",
            "InvalidArgumentException",
            "LogicException"
        ],
        "parents": [],
        "implements": [],
        "lcom": 4,
        "length": 109,
        "vocabulary": 30,
        "volume": 534.85,
        "difficulty": 15.86,
        "effort": 8481.21,
        "level": 0.06,
        "bugs": 0.18,
        "time": 471,
        "intelligentContent": 33.73,
        "number_operators": 35,
        "number_operands": 74,
        "number_operators_unique": 9,
        "number_operands_unique": 21,
        "cloc": 29,
        "loc": 111,
        "lloc": 82,
        "mi": 72.71,
        "mIwoC": 37.13,
        "commentWeight": 35.58,
        "kanDefect": 0.71,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 11.09,
        "relativeSystemComplexity": 11.09,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 122,
        "totalSystemComplexity": 122,
        "package": "Snicco\\Component\\BetterWPMail\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 4,
        "instability": 0.57,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "withTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withCc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addCc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withBcc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addBcc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withSender",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withReturnPath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withSubject",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withReplyTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addReplyTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withFrom",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addFrom",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addAttachment",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addBinaryAttachment",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addEmbed",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addBinaryEmbed",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withPriority",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withHtmlTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withHtmlBody",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withTextBody",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withTextTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withContext",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addContext",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addCustomHeaders",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withCustomHeaders",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "to",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bcc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "subject",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sender",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "returnPath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "replyTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "from",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "attachments",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "priority",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "htmlTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "textBody",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "htmlBody",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "textTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "context",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "customHeaders",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "textCharset",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "htmlCharset",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "_addContext",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "_addCustomHeader",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "normalizeAddresses",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 47,
        "nbMethods": 42,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 39,
        "nbMethodsGetter": 5,
        "nbMethodsSetters": 0,
        "wmc": 63,
        "ccn": 22,
        "ccnMethodMax": 6,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Attachment",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Attachment",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Attachment",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Attachment",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "InvalidArgumentException",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox"
        ],
        "parents": [],
        "implements": [],
        "lcom": 17,
        "length": 409,
        "vocabulary": 36,
        "volume": 2114.5,
        "difficulty": 40.14,
        "effort": 84882.04,
        "level": 0.02,
        "bugs": 0.7,
        "time": 4716,
        "intelligentContent": 52.67,
        "number_operators": 128,
        "number_operands": 281,
        "number_operators_unique": 8,
        "number_operands_unique": 28,
        "cloc": 139,
        "loc": 443,
        "lloc": 304,
        "mi": 57.74,
        "mIwoC": 19.6,
        "commentWeight": 38.14,
        "kanDefect": 1.86,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 4.99,
        "relativeSystemComplexity": 85.99,
        "totalStructuralComplexity": 3807,
        "totalDataComplexity": 234.4,
        "totalSystemComplexity": 4041.4,
        "package": "Snicco\\Component\\BetterWPMail\\ValueObject\\",
        "pageRank": 0.01,
        "afferentCoupling": 9,
        "efferentCoupling": 6,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Renderer\\FilesystemRenderer",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "supports",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\Renderer\\MailRenderer"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\BetterWPMail\\Renderer\\MailRenderer"
        ],
        "lcom": 2,
        "length": 22,
        "vocabulary": 12,
        "volume": 78.87,
        "difficulty": 4,
        "effort": 315.48,
        "level": 0.25,
        "bugs": 0.03,
        "time": 18,
        "intelligentContent": 19.72,
        "number_operators": 6,
        "number_operands": 16,
        "number_operators_unique": 4,
        "number_operands_unique": 8,
        "cloc": 3,
        "loc": 24,
        "lloc": 21,
        "mi": 83.51,
        "mIwoC": 57.47,
        "commentWeight": 26.04,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 5,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 10,
        "totalSystemComplexity": 10,
        "package": "Snicco\\Component\\BetterWPMail\\Renderer\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Renderer\\AggregateRenderer",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "supports",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 7,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\Renderer\\MailRenderer",
            "Snicco\\Component\\BetterWPMail\\Renderer\\MailRenderer",
            "Snicco\\Component\\BetterWPMail\\Exception\\CouldNotRenderMailContent"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\BetterWPMail\\Renderer\\MailRenderer"
        ],
        "lcom": 2,
        "length": 48,
        "vocabulary": 12,
        "volume": 172.08,
        "difficulty": 8.75,
        "effort": 1505.68,
        "level": 0.11,
        "bugs": 0.06,
        "time": 84,
        "intelligentContent": 19.67,
        "number_operators": 13,
        "number_operands": 35,
        "number_operators_unique": 4,
        "number_operands_unique": 8,
        "cloc": 11,
        "loc": 45,
        "lloc": 34,
        "mi": 84.79,
        "mIwoC": 50.13,
        "commentWeight": 34.66,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.56,
        "relativeSystemComplexity": 5.56,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 4.67,
        "totalSystemComplexity": 16.67,
        "package": "Snicco\\Component\\BetterWPMail\\Renderer\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Transport\\WPMailTransport",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "send",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handleFailure",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "justInTimeConfiguration",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTo",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "stringifyAddresses",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resetPHPMailer",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 5,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 24,
        "ccn": 18,
        "ccnMethodMax": 10,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\Transport\\Transport",
            "Snicco\\Component\\BetterWPMail\\WPMailAPI",
            "Snicco\\Component\\BetterWPMail\\WPMailAPI",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\Exception\\CantSendEmailWithWPMail",
            "Snicco\\Component\\BetterWPMail\\Exception\\CantSendEmailWithWPMail",
            "Snicco\\Component\\BetterWPMail\\Exception\\CantSendEmailWithWPMail",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\BetterWPMail\\Transport\\Transport"
        ],
        "lcom": 1,
        "length": 229,
        "vocabulary": 60,
        "volume": 1352.68,
        "difficulty": 13.08,
        "effort": 17688.87,
        "level": 0.08,
        "bugs": 0.45,
        "time": 983,
        "intelligentContent": 103.44,
        "number_operators": 59,
        "number_operands": 170,
        "number_operators_unique": 8,
        "number_operands_unique": 52,
        "cloc": 30,
        "loc": 140,
        "lloc": 110,
        "mi": 63.98,
        "mIwoC": 31.12,
        "commentWeight": 32.86,
        "kanDefect": 1.63,
        "relativeStructuralComplexity": 1369,
        "relativeDataComplexity": 0.14,
        "relativeSystemComplexity": 1369.14,
        "totalStructuralComplexity": 9583,
        "totalDataComplexity": 0.95,
        "totalSystemComplexity": 9583.95,
        "package": "Snicco\\Component\\BetterWPMail\\Transport\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 6,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Testing\\FakeTransport",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "send",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "interceptWordPressEmails",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "reset",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "assertNotSent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "assertSentTimes",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "assertSentTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "assertSent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "assertNotSentTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "recordMail",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "recordWPMail",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sentEmailsThatMatchCondition",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "wasSent",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 13,
        "nbMethods": 13,
        "nbMethodsPrivate": 4,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 39,
        "ccn": 27,
        "ccnMethodMax": 14,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\Transport\\Transport",
            "Snicco\\Component\\BetterWPMail\\WPMailAPI",
            "Snicco\\Component\\BetterWPMail\\WPMailAPI",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
            "RuntimeException",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "RuntimeException",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\Testing\\WPMail",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
            "Closure"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\BetterWPMail\\Transport\\Transport"
        ],
        "lcom": 1,
        "length": 332,
        "vocabulary": 71,
        "volume": 2041.72,
        "difficulty": 18.51,
        "effort": 37788.21,
        "level": 0.05,
        "bugs": 0.68,
        "time": 2099,
        "intelligentContent": 110.31,
        "number_operators": 77,
        "number_operands": 255,
        "number_operators_unique": 9,
        "number_operands_unique": 62,
        "cloc": 29,
        "loc": 175,
        "lloc": 146,
        "mi": 55.46,
        "mIwoC": 25.98,
        "commentWeight": 29.48,
        "kanDefect": 1.98,
        "relativeStructuralComplexity": 484,
        "relativeDataComplexity": 0.23,
        "relativeSystemComplexity": 484.23,
        "totalStructuralComplexity": 6292,
        "totalDataComplexity": 3.04,
        "totalSystemComplexity": 6295.04,
        "package": "Snicco\\Component\\BetterWPMail\\Testing\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 10,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Testing\\WPMail",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email"
        ],
        "parents": [
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email"
        ],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Snicco\\Component\\BetterWPMail\\Testing\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    }
]