var classes = [
    {
        "name": "Snicco\\Component\\BetterWPMail\\Testing\\FakeTransport",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "send",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "interceptWordPressEmails",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "reset",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "assertNotSent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "assertSentTimes",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "assertSentTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "assertSent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "assertNotSentTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "recordMail",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "recordWPMail",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sentEmailsThatMatchCondition",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "wasSent",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 13,
        "nbMethods": 13,
        "nbMethodsPrivate": 4,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 39,
        "ccn": 27,
        "ccnMethodMax": 14,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\Transport\\Transport",
            "Snicco\\Component\\BetterWPMail\\WPMailAPI",
            "Snicco\\Component\\BetterWPMail\\WPMailAPI",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
            "RuntimeException",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "RuntimeException",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\Testing\\WPMail",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
            "Closure"
        ],
        "parents": [],
        "lcom": 1,
        "length": 334,
        "vocabulary": 72,
        "volume": 2060.75,
        "difficulty": 18.43,
        "effort": 37976.77,
        "level": 0.05,
        "bugs": 0.69,
        "time": 2110,
        "intelligentContent": 111.82,
        "number_operators": 76,
        "number_operands": 258,
        "number_operators_unique": 9,
        "number_operands_unique": 63,
        "cloc": 25,
        "loc": 176,
        "lloc": 151,
        "mi": 53.19,
        "mIwoC": 25.63,
        "commentWeight": 27.56,
        "kanDefect": 1.98,
        "relativeStructuralComplexity": 484,
        "relativeDataComplexity": 0.32,
        "relativeSystemComplexity": 484.32,
        "totalStructuralComplexity": 6292,
        "totalDataComplexity": 4.17,
        "totalSystemComplexity": 6296.17,
        "package": "Snicco\\Component\\BetterWPMail\\Testing\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 10,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Testing\\WPMail",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email"
        ],
        "parents": [
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Snicco\\Component\\BetterWPMail\\Testing\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Transport\\WPMailTransport",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "send",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handleFailure",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "justInTimeConfiguration",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTo",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "stringifyAddresses",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resetPHPMailer",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 5,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 24,
        "ccn": 18,
        "ccnMethodMax": 10,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\Transport\\Transport",
            "Snicco\\Component\\BetterWPMail\\WPMailAPI",
            "Snicco\\Component\\BetterWPMail\\WPMailAPI",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\Exception\\CantSendEmailWithWPMail",
            "Snicco\\Component\\BetterWPMail\\Exception\\CantSendEmailWithWPMail",
            "Closure",
            "Snicco\\Component\\BetterWPMail\\Exception\\CantSendEmailWithWPMail",
            "Closure",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList"
        ],
        "parents": [],
        "lcom": 1,
        "length": 225,
        "vocabulary": 59,
        "volume": 1323.59,
        "difficulty": 11.31,
        "effort": 14966.8,
        "level": 0.09,
        "bugs": 0.44,
        "time": 831,
        "intelligentContent": 117.05,
        "number_operators": 57,
        "number_operands": 168,
        "number_operators_unique": 7,
        "number_operands_unique": 52,
        "cloc": 30,
        "loc": 138,
        "lloc": 108,
        "mi": 64.42,
        "mIwoC": 31.36,
        "commentWeight": 33.06,
        "kanDefect": 1.63,
        "relativeStructuralComplexity": 1369,
        "relativeDataComplexity": 0.14,
        "relativeSystemComplexity": 1369.14,
        "totalStructuralComplexity": 9583,
        "totalDataComplexity": 0.95,
        "totalSystemComplexity": 9583.95,
        "package": "Snicco\\Component\\BetterWPMail\\Transport\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 7,
        "instability": 0.88,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Mailer",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "send",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fireSendingEvent",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "prepareAndValidate",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "determineSender",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "mergeRecipientsFromHeaders",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fireSentEvent",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 5,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 25,
        "ccn": 19,
        "ccnMethodMax": 13,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\Transport\\WPMailTransport",
            "Snicco\\Component\\BetterWPMail\\Renderer\\FilesystemRenderer",
            "Snicco\\Component\\BetterWPMail\\Renderer\\AggregateRenderer",
            "Snicco\\Component\\BetterWPMail\\Event\\NullEvents",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailDefaults",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\Event\\SendingEmail",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
            "Snicco\\Component\\BetterWPMail\\Event\\SendingEmail",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "LogicException",
            "LogicException",
            "LogicException",
            "LogicException",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "LogicException",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
            "Snicco\\Component\\BetterWPMail\\Event\\EmailWasSent"
        ],
        "parents": [],
        "lcom": 1,
        "length": 149,
        "vocabulary": 28,
        "volume": 716.3,
        "difficulty": 14.32,
        "effort": 10256.05,
        "level": 0.07,
        "bugs": 0.24,
        "time": 570,
        "intelligentContent": 50.03,
        "number_operators": 44,
        "number_operands": 105,
        "number_operators_unique": 6,
        "number_operands_unique": 22,
        "cloc": 7,
        "loc": 88,
        "lloc": 81,
        "mi": 56.98,
        "mIwoC": 35.82,
        "commentWeight": 21.16,
        "kanDefect": 0.85,
        "relativeStructuralComplexity": 961,
        "relativeDataComplexity": 0.17,
        "relativeSystemComplexity": 961.17,
        "totalStructuralComplexity": 6727,
        "totalDataComplexity": 1.22,
        "totalSystemComplexity": 6728.22,
        "package": "Snicco\\Component\\BetterWPMail\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 12,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "name",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "address",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isEmailValid",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 5,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 22,
        "ccn": 16,
        "ccnMethodMax": 12,
        "externals": [
            "InvalidArgumentException",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "LogicException"
        ],
        "parents": [],
        "lcom": 2,
        "length": 121,
        "vocabulary": 29,
        "volume": 587.82,
        "difficulty": 12.89,
        "effort": 7574.81,
        "level": 0.08,
        "bugs": 0.2,
        "time": 421,
        "intelligentContent": 45.62,
        "number_operators": 40,
        "number_operands": 81,
        "number_operators_unique": 7,
        "number_operands_unique": 22,
        "cloc": 12,
        "loc": 88,
        "lloc": 76,
        "mi": 64.5,
        "mIwoC": 37.43,
        "commentWeight": 27.07,
        "kanDefect": 0.92,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 2.54,
        "relativeSystemComplexity": 18.54,
        "totalStructuralComplexity": 112,
        "totalDataComplexity": 17.8,
        "totalSystemComplexity": 129.8,
        "package": "Snicco\\Component\\BetterWPMail\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 8,
        "efferentCoupling": 4,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "withTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withCc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addCc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withBcc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addBcc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withSender",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withReturnPath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withSubject",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withReplyTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addReplyTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withFrom",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addFrom",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addAttachment",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addBinaryAttachment",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addEmbed",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addBinaryEmbed",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withPriority",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withHtmlTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withHtmlBody",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withTextBody",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withTextTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withContext",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addContext",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addCustomHeaders",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withCustomHeaders",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "to",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bcc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "subject",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sender",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "returnPath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "replyTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "from",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "attachments",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "priority",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "htmlTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "textBody",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "htmlBody",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "textTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "context",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "customHeaders",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "textCharset",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "htmlCharset",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "_addAttachment",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "_setPriority",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "_addContext",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "_addCustomHeader",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "normalizeAddresses",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 49,
        "nbMethods": 44,
        "nbMethodsPrivate": 5,
        "nbMethodsPublic": 39,
        "nbMethodsGetter": 5,
        "nbMethodsSetters": 0,
        "wmc": 71,
        "ccn": 23,
        "ccnMethodMax": 6,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Attachment",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Attachment",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Attachment",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Attachment",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Attachment",
            "InvalidArgumentException",
            "LogicException",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox"
        ],
        "parents": [],
        "lcom": 17,
        "length": 421,
        "vocabulary": 38,
        "volume": 2209.38,
        "difficulty": 39.33,
        "effort": 86902.18,
        "level": 0.03,
        "bugs": 0.74,
        "time": 4828,
        "intelligentContent": 56.17,
        "number_operators": 126,
        "number_operands": 295,
        "number_operators_unique": 8,
        "number_operands_unique": 30,
        "cloc": 137,
        "loc": 453,
        "lloc": 316,
        "mi": 56.59,
        "mIwoC": 18.96,
        "commentWeight": 37.63,
        "kanDefect": 1.93,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 4.16,
        "relativeSystemComplexity": 125.16,
        "totalStructuralComplexity": 5929,
        "totalDataComplexity": 203.67,
        "totalSystemComplexity": 6132.67,
        "package": "Snicco\\Component\\BetterWPMail\\ValueObject\\",
        "pageRank": 0.01,
        "afferentCoupling": 9,
        "efferentCoupling": 7,
        "instability": 0.44,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "merge",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "count",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getIterator",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addAddress",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 5,
        "ccnMethodMax": 2,
        "externals": [
            "Countable",
            "IteratorAggregate",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "ArrayIterator",
            "ArrayIterator",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox"
        ],
        "parents": [],
        "lcom": 2,
        "length": 42,
        "vocabulary": 9,
        "volume": 133.14,
        "difficulty": 7.75,
        "effort": 1031.81,
        "level": 0.13,
        "bugs": 0.04,
        "time": 57,
        "intelligentContent": 17.18,
        "number_operators": 11,
        "number_operands": 31,
        "number_operators_unique": 3,
        "number_operands_unique": 6,
        "cloc": 25,
        "loc": 69,
        "lloc": 44,
        "mi": 88.76,
        "mIwoC": 48.6,
        "commentWeight": 40.16,
        "kanDefect": 0.68,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.31,
        "relativeSystemComplexity": 17.31,
        "totalStructuralComplexity": 112,
        "totalDataComplexity": 9.2,
        "totalSystemComplexity": 121.2,
        "package": "Snicco\\Component\\BetterWPMail\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 7,
        "efferentCoupling": 6,
        "instability": 0.46,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sender",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "recipients",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailboxList"
        ],
        "parents": [],
        "lcom": 1,
        "length": 20,
        "vocabulary": 9,
        "volume": 63.4,
        "difficulty": 3.5,
        "effort": 221.89,
        "level": 0.29,
        "bugs": 0.02,
        "time": 12,
        "intelligentContent": 18.11,
        "number_operators": 6,
        "number_operands": 14,
        "number_operators_unique": 3,
        "number_operands_unique": 6,
        "cloc": 3,
        "loc": 28,
        "lloc": 25,
        "mi": 80.77,
        "mIwoC": 56.48,
        "commentWeight": 24.28,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 2.33,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 7,
        "package": "Snicco\\Component\\BetterWPMail\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 5,
        "efferentCoupling": 3,
        "instability": 0.38,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\ValueObject\\MailDefaults",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromWordPressSettings",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFrom",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getReplyTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailDefaults",
            "Snicco\\Component\\BetterWPMail\\WPMailAPI",
            "Snicco\\Component\\BetterWPMail\\WPMailAPI",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\MailDefaults",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Mailbox"
        ],
        "parents": [],
        "lcom": 2,
        "length": 37,
        "vocabulary": 10,
        "volume": 122.91,
        "difficulty": 3.38,
        "effort": 414.83,
        "level": 0.3,
        "bugs": 0.04,
        "time": 23,
        "intelligentContent": 36.42,
        "number_operators": 10,
        "number_operands": 27,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 30,
        "lloc": 30,
        "mi": 52.88,
        "mIwoC": 52.88,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.06,
        "relativeSystemComplexity": 10.06,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 4.25,
        "totalSystemComplexity": 40.25,
        "package": "Snicco\\Component\\BetterWPMail\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 4,
        "instability": 0.57,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\ValueObject\\Attachment",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromPath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bodyAsString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "name",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "contentType",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isInline",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "disposition",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "encoding",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cid",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__destruct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 7,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 4,
        "nbMethodsSetters": 0,
        "wmc": 26,
        "ccn": 16,
        "ccnMethodMax": 5,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Attachment",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Attachment",
            "InvalidArgumentException",
            "LogicException"
        ],
        "parents": [],
        "lcom": 3,
        "length": 113,
        "vocabulary": 31,
        "volume": 559.82,
        "difficulty": 15.75,
        "effort": 8817.23,
        "level": 0.06,
        "bugs": 0.19,
        "time": 490,
        "intelligentContent": 35.54,
        "number_operators": 36,
        "number_operands": 77,
        "number_operators_unique": 9,
        "number_operands_unique": 22,
        "cloc": 25,
        "loc": 107,
        "lloc": 82,
        "mi": 70.9,
        "mIwoC": 36.86,
        "commentWeight": 34.04,
        "kanDefect": 0.71,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 5.55,
        "relativeSystemComplexity": 6.55,
        "totalStructuralComplexity": 11,
        "totalDataComplexity": 61,
        "totalSystemComplexity": 72,
        "package": "Snicco\\Component\\BetterWPMail\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 4,
        "instability": 0.57,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Event\\SendingEmail",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email"
        ],
        "parents": [],
        "lcom": 1,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 0.75,
        "effort": 4.75,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 8.45,
        "number_operators": 1,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 14,
        "lloc": 9,
        "mi": 113.39,
        "mIwoC": 73.43,
        "commentWeight": 39.96,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "Snicco\\Component\\BetterWPMail\\Event\\",
        "pageRank": 0,
        "afferentCoupling": 4,
        "efferentCoupling": 1,
        "instability": 0.2,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Event\\NullEvents",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "fireSending",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fireSent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\Event\\MailEvents",
            "Snicco\\Component\\BetterWPMail\\Event\\SendingEmail",
            "Snicco\\Component\\BetterWPMail\\Event\\EmailWasSent"
        ],
        "parents": [],
        "lcom": 2,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 2,
        "loc": 12,
        "lloc": 10,
        "mi": 105.5,
        "mIwoC": 75.94,
        "commentWeight": 29.56,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "Snicco\\Component\\BetterWPMail\\Event\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Event\\EmailWasSent",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "email",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "envelope",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Email",
            "Snicco\\Component\\BetterWPMail\\ValueObject\\Envelope"
        ],
        "parents": [],
        "lcom": 1,
        "length": 12,
        "vocabulary": 5,
        "volume": 27.86,
        "difficulty": 2.67,
        "effort": 74.3,
        "level": 0.38,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 10.45,
        "number_operators": 4,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 19,
        "lloc": 19,
        "mi": 61.85,
        "mIwoC": 61.85,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.67,
        "relativeSystemComplexity": 2.67,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 8,
        "package": "Snicco\\Component\\BetterWPMail\\Event\\",
        "pageRank": 0,
        "afferentCoupling": 4,
        "efferentCoupling": 2,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Event\\MailEventsUsingWPHooks",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fireSending",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fireSent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\Event\\MailEvents",
            "Snicco\\Component\\BetterWPMail\\WPMailAPI",
            "Snicco\\Component\\BetterWPMail\\Event\\SendingEmail",
            "Snicco\\Component\\BetterWPMail\\Event\\EmailWasSent"
        ],
        "parents": [],
        "lcom": 1,
        "length": 11,
        "vocabulary": 5,
        "volume": 25.54,
        "difficulty": 1.25,
        "effort": 31.93,
        "level": 0.8,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 20.43,
        "number_operators": 1,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 17,
        "lloc": 17,
        "mi": 63.17,
        "mIwoC": 63.17,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 4.5,
        "package": "Snicco\\Component\\BetterWPMail\\Event\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\WPMailAPI",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "mail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "adminEmail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "siteName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "siteUrl",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\BetterWPAPI\\BetterWPAPI"
        ],
        "parents": [
            "Snicco\\Component\\BetterWPAPI\\BetterWPAPI"
        ],
        "lcom": 3,
        "length": 21,
        "vocabulary": 12,
        "volume": 75.28,
        "difficulty": 0.77,
        "effort": 58.17,
        "level": 1.29,
        "bugs": 0.03,
        "time": 3,
        "intelligentContent": 97.43,
        "number_operators": 4,
        "number_operands": 17,
        "number_operators_unique": 1,
        "number_operands_unique": 11,
        "cloc": 18,
        "loc": 38,
        "lloc": 20,
        "mi": 102.11,
        "mIwoC": 58.34,
        "commentWeight": 43.77,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.63,
        "relativeSystemComplexity": 3.63,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 10.5,
        "totalSystemComplexity": 14.5,
        "package": "Snicco\\Component\\BetterWPMail\\",
        "pageRank": 0,
        "afferentCoupling": 4,
        "efferentCoupling": 1,
        "instability": 0.2,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Exception\\CantSendEmailWithWPMail",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "becauseWPMailRaisedErrors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDebugData",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "RuntimeException",
            "Snicco\\Component\\BetterWPMail\\Exception\\CantSendEmail",
            "Throwable",
            "Snicco\\Component\\BetterWPMail\\Exception\\CantSendEmailWithWPMail",
            "WP_Error"
        ],
        "parents": [
            "RuntimeException"
        ],
        "lcom": 2,
        "length": 34,
        "vocabulary": 17,
        "volume": 138.97,
        "difficulty": 1.87,
        "effort": 259.42,
        "level": 0.54,
        "bugs": 0.05,
        "time": 14,
        "intelligentContent": 74.45,
        "number_operators": 6,
        "number_operands": 28,
        "number_operators_unique": 2,
        "number_operands_unique": 15,
        "cloc": 1,
        "loc": 22,
        "lloc": 21,
        "mi": 72.23,
        "mIwoC": 56.02,
        "commentWeight": 16.22,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.11,
        "relativeSystemComplexity": 5.11,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 3.33,
        "totalSystemComplexity": 15.33,
        "package": "Snicco\\Component\\BetterWPMail\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 6,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Exception\\CantRenderMailContent",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "RuntimeException"
        ],
        "parents": [
            "RuntimeException"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Snicco\\Component\\BetterWPMail\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Renderer\\AggregateRenderer",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMailContent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "supports",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 8,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\Renderer\\MailRenderer",
            "Snicco\\Component\\BetterWPMail\\Renderer\\MailRenderer",
            "Snicco\\Component\\BetterWPMail\\Exception\\CantRenderMailContent"
        ],
        "parents": [],
        "lcom": 2,
        "length": 49,
        "vocabulary": 13,
        "volume": 181.32,
        "difficulty": 5.55,
        "effort": 1006.33,
        "level": 0.18,
        "bugs": 0.06,
        "time": 56,
        "intelligentContent": 32.67,
        "number_operators": 12,
        "number_operands": 37,
        "number_operators_unique": 3,
        "number_operands_unique": 10,
        "cloc": 11,
        "loc": 45,
        "lloc": 34,
        "mi": 84.63,
        "mIwoC": 49.97,
        "commentWeight": 34.66,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.56,
        "relativeSystemComplexity": 5.56,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 4.67,
        "totalSystemComplexity": 16.67,
        "package": "Snicco\\Component\\BetterWPMail\\Renderer\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\BetterWPMail\\Renderer\\FilesystemRenderer",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "getMailContent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "supports",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\BetterWPMail\\Renderer\\MailRenderer"
        ],
        "parents": [],
        "lcom": 2,
        "length": 23,
        "vocabulary": 13,
        "volume": 85.11,
        "difficulty": 3.78,
        "effort": 321.53,
        "level": 0.26,
        "bugs": 0.03,
        "time": 18,
        "intelligentContent": 22.53,
        "number_operators": 6,
        "number_operands": 17,
        "number_operators_unique": 4,
        "number_operands_unique": 9,
        "cloc": 3,
        "loc": 24,
        "lloc": 21,
        "mi": 83.28,
        "mIwoC": 57.24,
        "commentWeight": 26.04,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 5,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 10,
        "totalSystemComplexity": 10,
        "package": "Snicco\\Component\\BetterWPMail\\Renderer\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    }
]