var classes = [
    {
        "name": "Snicco\\Component\\Session\\Event\\SessionRotated",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Snicco\\Component\\Session\\ImmutableSession"
        ],
        "parents": [],
        "implements": [],
        "lcom": 0,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 0.75,
        "effort": 4.75,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 8.45,
        "number_operators": 1,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 9,
        "lloc": 9,
        "mi": 73.43,
        "mIwoC": 73.43,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "Snicco\\Component\\Session\\Event\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Serializer\\PHPSerializer",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "serialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deserialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Snicco\\Component\\Session\\Serializer\\Serializer",
            "RuntimeException",
            "RuntimeException"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Session\\Serializer\\Serializer"
        ],
        "lcom": 2,
        "length": 17,
        "vocabulary": 10,
        "volume": 56.47,
        "difficulty": 5,
        "effort": 282.36,
        "level": 0.2,
        "bugs": 0.02,
        "time": 16,
        "intelligentContent": 11.29,
        "number_operators": 7,
        "number_operands": 10,
        "number_operators_unique": 5,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 19,
        "lloc": 19,
        "mi": 59.44,
        "mIwoC": 59.44,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 6,
        "package": "Snicco\\Component\\Session\\Serializer\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Serializer\\JsonSerializer",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "serialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deserialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\Session\\Serializer\\Serializer",
            "InvalidArgumentException"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Session\\Serializer\\Serializer"
        ],
        "lcom": 2,
        "length": 17,
        "vocabulary": 10,
        "volume": 56.47,
        "difficulty": 4,
        "effort": 225.89,
        "level": 0.25,
        "bugs": 0.02,
        "time": 13,
        "intelligentContent": 14.12,
        "number_operators": 5,
        "number_operands": 12,
        "number_operators_unique": 4,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 61.2,
        "mIwoC": 61.2,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 6,
        "package": "Snicco\\Component\\Session\\Serializer\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Exception\\CouldNotWriteSessionContent",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "forId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "RuntimeException",
            "Snicco\\Component\\Session\\Exception\\CouldNotWriteSessionContent",
            "Throwable"
        ],
        "parents": [
            "RuntimeException"
        ],
        "implements": [],
        "lcom": 1,
        "length": 9,
        "vocabulary": 6,
        "volume": 23.26,
        "difficulty": 0.8,
        "effort": 18.61,
        "level": 1.25,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 29.08,
        "number_operators": 1,
        "number_operands": 8,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 70.6,
        "mIwoC": 70.6,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "package": "Snicco\\Component\\Session\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 4,
        "instability": 0.57,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Exception\\UnknownSessionSelector",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "forSelector",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "InvalidArgumentException",
            "Snicco\\Component\\Session\\Exception\\UnknownSessionSelector"
        ],
        "parents": [
            "InvalidArgumentException"
        ],
        "implements": [],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 0.83,
        "effort": 10,
        "level": 1.2,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 14.4,
        "number_operators": 1,
        "number_operands": 5,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 72.61,
        "mIwoC": 72.61,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "Snicco\\Component\\Session\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 5,
        "efferentCoupling": 3,
        "instability": 0.38,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Exception\\CouldNotDestroySession",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "forSelector",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "RuntimeException",
            "Snicco\\Component\\Session\\Exception\\CouldNotDestroySession",
            "Throwable"
        ],
        "parents": [
            "RuntimeException"
        ],
        "implements": [],
        "lcom": 1,
        "length": 13,
        "vocabulary": 8,
        "volume": 39,
        "difficulty": 1.83,
        "effort": 71.5,
        "level": 0.55,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 21.27,
        "number_operators": 2,
        "number_operands": 11,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 68.89,
        "mIwoC": 68.89,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 3,
        "package": "Snicco\\Component\\Session\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 4,
        "efferentCoupling": 4,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Exception\\CouldNotReadSessionContent",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "forID",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "RuntimeException",
            "Snicco\\Component\\Session\\Exception\\CouldNotReadSessionContent",
            "Snicco\\Component\\Session\\Exception\\CouldNotReadSessionContent"
        ],
        "parents": [
            "RuntimeException"
        ],
        "implements": [],
        "lcom": 1,
        "length": 13,
        "vocabulary": 8,
        "volume": 39,
        "difficulty": 1.83,
        "effort": 71.5,
        "level": 0.55,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 21.27,
        "number_operators": 2,
        "number_operands": 11,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 68.89,
        "mIwoC": 68.89,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 3,
        "package": "Snicco\\Component\\Session\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 3,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Exception\\SessionIsLocked",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "LogicException",
            "Throwable"
        ],
        "parents": [
            "LogicException"
        ],
        "implements": [],
        "lcom": 1,
        "length": 8,
        "vocabulary": 5,
        "volume": 18.58,
        "difficulty": 0,
        "effort": 0,
        "level": 1.25,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 8,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 71.28,
        "mIwoC": 71.28,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 2.5,
        "package": "Snicco\\Component\\Session\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\ValueObject\\SessionId",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromCookieId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "new",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "asString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sameAs",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "selector",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validator",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "newTokens",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 7,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "ParagonIE\\ConstantTime\\Binary",
            "ParagonIE\\ConstantTime\\Binary",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "ParagonIE\\ConstantTime\\Base64UrlSafe",
            "ParagonIE\\ConstantTime\\Base64UrlSafe"
        ],
        "parents": [],
        "implements": [],
        "lcom": 3,
        "length": 64,
        "vocabulary": 22,
        "volume": 285.4,
        "difficulty": 11.71,
        "effort": 3343.3,
        "level": 0.09,
        "bugs": 0.1,
        "time": 186,
        "intelligentContent": 24.36,
        "number_operators": 23,
        "number_operands": 41,
        "number_operators_unique": 8,
        "number_operands_unique": 14,
        "cloc": 3,
        "loc": 52,
        "lloc": 49,
        "mi": 63.44,
        "mIwoC": 45.26,
        "commentWeight": 18.18,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.69,
        "relativeSystemComplexity": 17.69,
        "totalStructuralComplexity": 144,
        "totalDataComplexity": 15.2,
        "totalSystemComplexity": 159.2,
        "package": "Snicco\\Component\\Session\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 7,
        "efferentCoupling": 4,
        "instability": 0.36,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\ValueObject\\CookiePool",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromSuperGlobals",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\Session\\ValueObject\\CookiePool",
            "Snicco\\Component\\Session\\ValueObject\\CookiePool"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 15,
        "vocabulary": 7,
        "volume": 42.11,
        "difficulty": 3.75,
        "effort": 157.91,
        "level": 0.27,
        "bugs": 0.01,
        "time": 9,
        "intelligentContent": 11.23,
        "number_operators": 5,
        "number_operands": 10,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 17,
        "loc": 38,
        "lloc": 21,
        "mi": 102.54,
        "mIwoC": 59.51,
        "commentWeight": 43.02,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.75,
        "relativeSystemComplexity": 3.75,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 15,
        "totalSystemComplexity": 15,
        "package": "Snicco\\Component\\Session\\ValueObject\\",
        "pageRank": 0.62,
        "afferentCoupling": 6,
        "efferentCoupling": 2,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\ValueObject\\ReadOnlySession",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromSession",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boolean",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createdAt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "exists",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasOldInput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "id",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lastActivity",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lastRotation",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "missing",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "oldInput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "only",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "userId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isNew",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 17,
        "nbMethods": 16,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 16,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 16,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\Session\\ImmutableSession",
            "Snicco\\Component\\Session\\Session",
            "Snicco\\Component\\Session\\ValueObject\\ReadOnlySession",
            "Snicco\\Component\\Session\\Session",
            "Snicco\\Component\\Session\\ValueObject\\ReadOnlySession",
            "Snicco\\Component\\Session\\ValueObject\\SessionId"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Session\\ImmutableSession"
        ],
        "lcom": 2,
        "length": 59,
        "vocabulary": 7,
        "volume": 165.63,
        "difficulty": 8.4,
        "effort": 1391.33,
        "level": 0.12,
        "bugs": 0.06,
        "time": 77,
        "intelligentContent": 19.72,
        "number_operators": 17,
        "number_operands": 42,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 73,
        "lloc": 73,
        "mi": 43.68,
        "mIwoC": 43.68,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 225,
        "relativeDataComplexity": 1.05,
        "relativeSystemComplexity": 226.05,
        "totalStructuralComplexity": 3825,
        "totalDataComplexity": 17.81,
        "totalSystemComplexity": 3842.81,
        "package": "Snicco\\Component\\Session\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 4,
        "efferentCoupling": 5,
        "instability": 0.56,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lastActivity",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "data",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hashedValidator",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "userId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 4,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "InvalidArgumentException",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 41,
        "vocabulary": 13,
        "volume": 151.72,
        "difficulty": 8.75,
        "effort": 1327.53,
        "level": 0.11,
        "bugs": 0.05,
        "time": 74,
        "intelligentContent": 17.34,
        "number_operators": 13,
        "number_operands": 28,
        "number_operators_unique": 5,
        "number_operands_unique": 8,
        "cloc": 13,
        "loc": 51,
        "lloc": 38,
        "mi": 84.97,
        "mIwoC": 49.73,
        "commentWeight": 35.24,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 6.33,
        "relativeSystemComplexity": 6.33,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 38,
        "totalSystemComplexity": 38,
        "package": "Snicco\\Component\\Session\\ValueObject\\",
        "pageRank": 0.01,
        "afferentCoupling": 11,
        "efferentCoupling": 3,
        "instability": 0.21,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\ValueObject\\SessionLottery",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "wins",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "LogicException",
            "LogicException"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 19,
        "vocabulary": 12,
        "volume": 68.11,
        "difficulty": 4.29,
        "effort": 291.92,
        "level": 0.23,
        "bugs": 0.02,
        "time": 16,
        "intelligentContent": 15.89,
        "number_operators": 7,
        "number_operands": 12,
        "number_operators_unique": 5,
        "number_operands_unique": 7,
        "cloc": 7,
        "loc": 26,
        "lloc": 19,
        "mi": 94.87,
        "mIwoC": 58.87,
        "commentWeight": 36,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "Snicco\\Component\\Session\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\ValueObject\\SessionConfig",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromDefaults",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "mergeDefaults",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cookiePath",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cookieName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cookieDomain",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sameSite",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onlyHttp",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onlySecure",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "absoluteLifetimeInSec",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "idleTimeoutInSec",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rotationInterval",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "gcLottery",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 13,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 9,
        "nbMethodsSetters": 0,
        "wmc": 18,
        "ccn": 15,
        "ccnMethodMax": 15,
        "externals": [
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "Snicco\\Component\\Session\\ValueObject\\SessionConfig",
            "Snicco\\Component\\Session\\ValueObject\\SessionConfig",
            "Snicco\\Component\\Session\\ValueObject\\SessionConfig",
            "Snicco\\Component\\Session\\ValueObject\\SessionConfig",
            "Snicco\\Component\\Session\\ValueObject\\SessionLottery",
            "Snicco\\Component\\Session\\ValueObject\\SessionLottery"
        ],
        "parents": [],
        "implements": [],
        "lcom": 3,
        "length": 161,
        "vocabulary": 42,
        "volume": 868.16,
        "difficulty": 17.81,
        "effort": 15464.16,
        "level": 0.06,
        "bugs": 0.29,
        "time": 859,
        "intelligentContent": 48.74,
        "number_operators": 47,
        "number_operands": 114,
        "number_operators_unique": 10,
        "number_operands_unique": 32,
        "cloc": 43,
        "loc": 138,
        "lloc": 95,
        "mi": 72.31,
        "mIwoC": 34.26,
        "commentWeight": 38.05,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 12.31,
        "relativeSystemComplexity": 12.31,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 160,
        "totalSystemComplexity": 160,
        "package": "Snicco\\Component\\Session\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 4,
        "efferentCoupling": 4,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\ValueObject\\SessionCookie",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "value",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "name",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sameSite",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "path",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "domain",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "secureOnly",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "httpOnly",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "expiryTimestamp",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lifetime",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 8,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 58,
        "vocabulary": 17,
        "volume": 237.07,
        "difficulty": 7.71,
        "effort": 1827.44,
        "level": 0.13,
        "bugs": 0.08,
        "time": 102,
        "intelligentContent": 30.76,
        "number_operators": 21,
        "number_operands": 37,
        "number_operators_unique": 5,
        "number_operands_unique": 12,
        "cloc": 21,
        "loc": 83,
        "lloc": 62,
        "mi": 79.14,
        "mIwoC": 44,
        "commentWeight": 35.14,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 10.8,
        "relativeSystemComplexity": 10.8,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 108,
        "totalSystemComplexity": 108,
        "package": "Snicco\\Component\\Session\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\SessionManager\\SessionManger",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "start",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toCookie",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "gc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parseSessionId",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadSessionFromDriver",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isIdle",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "needsRotation",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isExpired",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hash",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 11,
        "nbMethodsPrivate": 6,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 23,
        "ccn": 13,
        "ccnMethodMax": 4,
        "externals": [
            "Snicco\\Component\\Session\\SessionManager\\SessionManagerInterface",
            "Snicco\\Component\\Session\\ValueObject\\SessionConfig",
            "Snicco\\Component\\Session\\Driver\\SessionDriver",
            "Snicco\\Component\\Session\\Serializer\\Serializer",
            "Snicco\\Component\\TestableClock\\SystemClock",
            "Snicco\\Component\\Session\\EventDispatcher\\NullSessionDispatcher",
            "Snicco\\Component\\Session\\Session",
            "Snicco\\Component\\Session\\ValueObject\\CookiePool",
            "Snicco\\Component\\Session\\Session",
            "Snicco\\Component\\Session\\ValueObject\\SessionCookie",
            "Snicco\\Component\\Session\\ImmutableSession",
            "Snicco\\Component\\Session\\ValueObject\\SessionCookie",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ValueObject\\CookiePool",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ReadWriteSession",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "RuntimeException",
            "Snicco\\Component\\Session\\ReadWriteSession",
            "Snicco\\Component\\Session\\ReadWriteSession",
            "Snicco\\Component\\Session\\Session",
            "Snicco\\Component\\Session\\Session",
            "Snicco\\Component\\Session\\Session",
            "RuntimeException"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Session\\SessionManager\\SessionManagerInterface"
        ],
        "lcom": 1,
        "length": 162,
        "vocabulary": 36,
        "volume": 837.53,
        "difficulty": 19.33,
        "effort": 16192.21,
        "level": 0.05,
        "bugs": 0.28,
        "time": 900,
        "intelligentContent": 43.32,
        "number_operators": 46,
        "number_operands": 116,
        "number_operators_unique": 9,
        "number_operands_unique": 27,
        "cloc": 9,
        "loc": 105,
        "lloc": 96,
        "mi": 56.45,
        "mIwoC": 34.54,
        "commentWeight": 21.91,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 1600,
        "relativeDataComplexity": 0.27,
        "relativeSystemComplexity": 1600.27,
        "totalStructuralComplexity": 17600,
        "totalDataComplexity": 3.02,
        "totalSystemComplexity": 17603.02,
        "package": "Snicco\\Component\\Session\\SessionManager\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 13,
        "instability": 0.93,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\ReadWriteSession",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createEmpty",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "put",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boolean",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createdAt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "decrement",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "increment",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "flashInput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "flash",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "push",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasOldInput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "oldInput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "id",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "invalidate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rotate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "flush",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "keep",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lastActivity",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lastRotation",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "flashNow",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "only",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "putIfMissing",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "missing",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "exists",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "reflash",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "releaseEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remove",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveUsing",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUserId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "userId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isNew",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isDirty",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "checkIfLocked",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeFromOldFlashData",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "oldFlashes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "recordEvent",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "mergeNewFlashes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "ageFlashData",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lock",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 42,
        "nbMethods": 39,
        "nbMethodsPrivate": 7,
        "nbMethodsPublic": 32,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "wmc": 70,
        "ccn": 32,
        "ccnMethodMax": 4,
        "externals": [
            "Snicco\\Component\\Session\\Session",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ReadWriteSession",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\StrArr\\Arr",
            "RuntimeException",
            "LogicException",
            "LogicException",
            "RuntimeException",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ValueObject\\ReadOnlySession",
            "Snicco\\Component\\Session\\Event\\SessionRotated",
            "RuntimeException",
            "Snicco\\Component\\StrArr\\Arr",
            "Closure",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\Session\\Driver\\SessionDriver",
            "Snicco\\Component\\Session\\Serializer\\Serializer",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "Snicco\\Component\\Session\\Exception\\SessionIsLocked",
            "Snicco\\Component\\StrArr\\Arr",
            "RuntimeException",
            "RuntimeException"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Session\\Session"
        ],
        "lcom": 2,
        "length": 397,
        "vocabulary": 57,
        "volume": 2315.66,
        "difficulty": 24.49,
        "effort": 56709.98,
        "level": 0.04,
        "bugs": 0.77,
        "time": 3151,
        "intelligentContent": 94.56,
        "number_operators": 97,
        "number_operands": 300,
        "number_operators_unique": 8,
        "number_operands_unique": 49,
        "cloc": 60,
        "loc": 362,
        "lloc": 302,
        "mi": 47.52,
        "mIwoC": 18.04,
        "commentWeight": 29.49,
        "kanDefect": 2.36,
        "relativeStructuralComplexity": 900,
        "relativeDataComplexity": 0.87,
        "relativeSystemComplexity": 900.87,
        "totalStructuralComplexity": 37800,
        "totalDataComplexity": 36.55,
        "totalSystemComplexity": 37836.55,
        "package": "Snicco\\Component\\Session\\",
        "pageRank": 0,
        "afferentCoupling": 4,
        "efferentCoupling": 15,
        "instability": 0.79,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\EventDispatcher\\NullSessionDispatcher",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "dispatchAll",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\Session\\EventDispatcher\\SessionEventDispatcher"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Session\\EventDispatcher\\SessionEventDispatcher"
        ],
        "lcom": 1,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 0,
        "loc": 7,
        "lloc": 7,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "Snicco\\Component\\Session\\EventDispatcher\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Driver\\InMemoryDriver",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "gc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "read",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "touch",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "write",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroyAllForAllUsers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroyAllForUserId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroyAllForUserIdExcept",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllForUserId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calculateExpiration",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 11,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 10,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 24,
        "ccn": 14,
        "ccnMethodMax": 4,
        "externals": [
            "Snicco\\Component\\Session\\Driver\\UserSessionsDriver",
            "Snicco\\Component\\TestableClock\\Clock",
            "Snicco\\Component\\TestableClock\\SystemClock",
            "Snicco\\Component\\Session\\Exception\\CouldNotDestroySession",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\Session\\Exception\\UnknownSessionSelector",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\Session\\Exception\\UnknownSessionSelector",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Session\\Driver\\UserSessionsDriver"
        ],
        "lcom": 1,
        "length": 126,
        "vocabulary": 25,
        "volume": 585.13,
        "difficulty": 23.29,
        "effort": 13629.99,
        "level": 0.04,
        "bugs": 0.2,
        "time": 757,
        "intelligentContent": 25.12,
        "number_operators": 27,
        "number_operands": 99,
        "number_operators_unique": 8,
        "number_operands_unique": 17,
        "cloc": 3,
        "loc": 91,
        "lloc": 88,
        "mi": 50.2,
        "mIwoC": 36.32,
        "commentWeight": 13.88,
        "kanDefect": 1.63,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.47,
        "relativeSystemComplexity": 100.47,
        "totalStructuralComplexity": 1200,
        "totalDataComplexity": 5.64,
        "totalSystemComplexity": 1205.64,
        "package": "Snicco\\Component\\Session\\Driver\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 6,
        "instability": 0.86,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Driver\\EncryptedDriver",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "gc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "read",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "touch",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "write",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroyAllForAllUsers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroyAllForUserId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroyAllForUserIdExcept",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllForUserId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 10,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 10,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 5,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\Session\\Driver\\UserSessionsDriver",
            "Snicco\\Component\\Session\\Driver\\SessionDriver",
            "Snicco\\Component\\Session\\SessionEncryptor",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "BadMethodCallException",
            "BadMethodCallException",
            "BadMethodCallException",
            "BadMethodCallException"
        ],
        "parents": [],
        "implements": [
            "Snicco\\Component\\Session\\Driver\\UserSessionsDriver"
        ],
        "lcom": 1,
        "length": 82,
        "vocabulary": 17,
        "volume": 335.17,
        "difficulty": 9.69,
        "effort": 3248.59,
        "level": 0.1,
        "bugs": 0.11,
        "time": 180,
        "intelligentContent": 34.58,
        "number_operators": 19,
        "number_operands": 63,
        "number_operators_unique": 4,
        "number_operands_unique": 13,
        "cloc": 0,
        "loc": 62,
        "lloc": 62,
        "mi": 42.55,
        "mIwoC": 42.55,
        "commentWeight": 0,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 256,
        "relativeDataComplexity": 0.19,
        "relativeSystemComplexity": 256.19,
        "totalStructuralComplexity": 2560,
        "totalDataComplexity": 1.94,
        "totalSystemComplexity": 2561.94,
        "package": "Snicco\\Component\\Session\\Driver\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Testing\\SessionDriverTests",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "read_from_session_throws_exception_for_bad_id",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "last_activity_is_stored_correctly",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "data_can_be_read_from_the_driver",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "data_can_be_written_to_an_existing_session",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "a_session_can_be_destroyed",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "garbage_collection_works_for_old_sessions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "touching_the_session_activity_works",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_touch_throws_exception_for_bad_id",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "travelIntoFuture",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "idleTimeout",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createDriver",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 11,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 4,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "DateTimeImmutable",
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\Driver\\SessionDriver",
            "Snicco\\Component\\TestableClock\\Clock"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 177,
        "vocabulary": 28,
        "volume": 850.9,
        "difficulty": 16.63,
        "effort": 14150.87,
        "level": 0.06,
        "bugs": 0.28,
        "time": 786,
        "intelligentContent": 51.17,
        "number_operators": 24,
        "number_operands": 153,
        "number_operators_unique": 5,
        "number_operands_unique": 23,
        "cloc": 35,
        "loc": 130,
        "lloc": 95,
        "mi": 71.81,
        "mIwoC": 35.8,
        "commentWeight": 36,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 289,
        "relativeDataComplexity": 0.07,
        "relativeSystemComplexity": 289.07,
        "totalStructuralComplexity": 3179,
        "totalDataComplexity": 0.78,
        "totalSystemComplexity": 3179.78,
        "package": "Snicco\\Component\\Session\\Testing\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Testing\\UserSessionDriverTests",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "all_sessions_for_all_users_can_be_destroyed",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all_sessions_for_a_specific_user_can_be_destroyed",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all_sessions_for_a_user_can_be_retrieved",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all_sessions_for_a_user_expect_one_can_be_destroyed",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createUserSessionDriver",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createSessions",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 19,
        "ccn": 14,
        "ccnMethodMax": 5,
        "externals": [
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\Session\\Driver\\UserSessionsDriver",
            "InvalidArgumentException",
            "Snicco\\Component\\Session\\Serializer\\JsonSerializer",
            "Snicco\\Component\\Session\\ReadWriteSession",
            "InvalidArgumentException",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 270,
        "vocabulary": 43,
        "volume": 1465.09,
        "difficulty": 26.63,
        "effort": 39013.29,
        "level": 0.04,
        "bugs": 0.49,
        "time": 2167,
        "intelligentContent": 55.02,
        "number_operators": 37,
        "number_operands": 233,
        "number_operators_unique": 8,
        "number_operands_unique": 35,
        "cloc": 30,
        "loc": 153,
        "lloc": 123,
        "mi": 62.03,
        "mIwoC": 30.36,
        "commentWeight": 31.67,
        "kanDefect": 1.51,
        "relativeStructuralComplexity": 324,
        "relativeDataComplexity": 0.08,
        "relativeSystemComplexity": 324.08,
        "totalStructuralComplexity": 1944,
        "totalDataComplexity": 0.47,
        "totalSystemComplexity": 1944.47,
        "package": "Snicco\\Component\\Session\\Testing\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    }
]