var classes = [
    {
        "name": "Snicco\\Component\\Session\\Testing\\UserSessionDriverTests",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "all_sessions_for_all_users_can_be_destroyed",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all_sessions_for_a_specific_user_can_be_destroyed",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all_sessions_for_a_user_can_be_retrieved",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all_sessions_for_a_user_expect_one_can_be_destroyed",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createUserSessionDriver",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createSessions",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 19,
        "ccn": 14,
        "ccnMethodMax": 5,
        "externals": [
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\Session\\Driver\\UserSessionsDriver",
            "InvalidArgumentException",
            "Snicco\\Component\\Session\\Serializer\\JsonSerializer",
            "InvalidArgumentException",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession"
        ],
        "parents": [],
        "lcom": 1,
        "length": 278,
        "vocabulary": 45,
        "volume": 1526.74,
        "difficulty": 26.16,
        "effort": 39942.69,
        "level": 0.04,
        "bugs": 0.51,
        "time": 2219,
        "intelligentContent": 58.36,
        "number_operators": 36,
        "number_operands": 242,
        "number_operators_unique": 8,
        "number_operands_unique": 37,
        "cloc": 32,
        "loc": 156,
        "lloc": 124,
        "mi": 62.43,
        "mIwoC": 30.16,
        "commentWeight": 32.27,
        "kanDefect": 1.51,
        "relativeStructuralComplexity": 324,
        "relativeDataComplexity": 0.08,
        "relativeSystemComplexity": 324.08,
        "totalStructuralComplexity": 1944,
        "totalDataComplexity": 0.47,
        "totalSystemComplexity": 1944.47,
        "package": "Snicco\\Component\\Session\\Testing\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Testing\\SessionDriverTests",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "read_from_session_throws_exception_for_bad_id",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "last_activity_is_stored_correctly",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "data_can_be_read_from_the_driver",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "data_can_be_written_to_an_existing_session",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "a_session_can_be_destroyed",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "multiple_session_ids_can_be_destroyed",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "garbage_collection_works_for_old_sessions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "touching_the_session_activity_works",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_touch_throws_exception_for_bad_id",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "travelIntoFuture",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "idleTimeout",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createDriver",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 12,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 17,
        "ccn": 6,
        "ccnMethodMax": 3,
        "externals": [
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "DateTimeImmutable",
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\TestableClock\\TestClock",
            "Snicco\\Component\\Session\\Driver\\SessionDriver",
            "Snicco\\Component\\TestableClock\\Clock"
        ],
        "parents": [],
        "lcom": 1,
        "length": 206,
        "vocabulary": 31,
        "volume": 1020.56,
        "difficulty": 17.21,
        "effort": 17565.48,
        "level": 0.06,
        "bugs": 0.34,
        "time": 976,
        "intelligentContent": 59.3,
        "number_operators": 27,
        "number_operands": 179,
        "number_operators_unique": 5,
        "number_operands_unique": 26,
        "cloc": 39,
        "loc": 153,
        "lloc": 114,
        "mi": 68.5,
        "mIwoC": 33.26,
        "commentWeight": 35.24,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 289,
        "relativeDataComplexity": 0.07,
        "relativeSystemComplexity": 289.07,
        "totalStructuralComplexity": 3468,
        "totalDataComplexity": 0.83,
        "totalSystemComplexity": 3468.83,
        "package": "Snicco\\Component\\Session\\Testing\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\ValueObject\\SessionConfig",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromDefaults",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cookiePath",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cookieName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cookieDomain",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sameSite",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onlyHttp",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onlySecure",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "absoluteLifetimeInSec",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "idleTimeoutInSec",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rotationInterval",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "gcLottery",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 9,
        "nbMethodsSetters": 0,
        "wmc": 26,
        "ccn": 15,
        "ccnMethodMax": 15,
        "externals": [
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "Snicco\\Component\\Session\\ValueObject\\SessionConfig",
            "Snicco\\Component\\Session\\ValueObject\\SessionConfig",
            "Snicco\\Component\\Session\\ValueObject\\SessionLottery",
            "Snicco\\Component\\Session\\ValueObject\\SessionLottery"
        ],
        "parents": [],
        "lcom": 2,
        "length": 139,
        "vocabulary": 42,
        "volume": 749.53,
        "difficulty": 14.84,
        "effort": 11125.87,
        "level": 0.07,
        "bugs": 0.25,
        "time": 618,
        "intelligentContent": 50.49,
        "number_operators": 44,
        "number_operands": 95,
        "number_operators_unique": 10,
        "number_operands_unique": 32,
        "cloc": 17,
        "loc": 112,
        "lloc": 95,
        "mi": 63.09,
        "mIwoC": 34.71,
        "commentWeight": 28.38,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 11.17,
        "relativeSystemComplexity": 11.17,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 134,
        "totalSystemComplexity": 134,
        "package": "Snicco\\Component\\Session\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 4,
        "instability": 0.57,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\ValueObject\\SessionId",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromCookieId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "new",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "asString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sameAs",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "selector",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validator",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "newTokens",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 7,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 13,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "ParagonIE\\ConstantTime\\Binary",
            "ParagonIE\\ConstantTime\\Binary",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "ParagonIE\\ConstantTime\\Base64UrlSafe",
            "ParagonIE\\ConstantTime\\Base64UrlSafe"
        ],
        "parents": [],
        "lcom": 3,
        "length": 64,
        "vocabulary": 22,
        "volume": 285.4,
        "difficulty": 11.71,
        "effort": 3343.3,
        "level": 0.09,
        "bugs": 0.1,
        "time": 186,
        "intelligentContent": 24.36,
        "number_operators": 23,
        "number_operands": 41,
        "number_operators_unique": 8,
        "number_operands_unique": 14,
        "cloc": 3,
        "loc": 52,
        "lloc": 49,
        "mi": 63.44,
        "mIwoC": 45.26,
        "commentWeight": 18.18,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.69,
        "relativeSystemComplexity": 17.69,
        "totalStructuralComplexity": 144,
        "totalDataComplexity": 15.2,
        "totalSystemComplexity": 159.2,
        "package": "Snicco\\Component\\Session\\ValueObject\\",
        "pageRank": 0.01,
        "afferentCoupling": 6,
        "efferentCoupling": 4,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lastActivity",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "data",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hashedValidator",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "userId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 4,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "InvalidArgumentException",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession"
        ],
        "parents": [],
        "lcom": 2,
        "length": 40,
        "vocabulary": 12,
        "volume": 143.4,
        "difficulty": 7,
        "effort": 1003.79,
        "level": 0.14,
        "bugs": 0.05,
        "time": 56,
        "intelligentContent": 20.49,
        "number_operators": 12,
        "number_operands": 28,
        "number_operators_unique": 4,
        "number_operands_unique": 8,
        "cloc": 13,
        "loc": 51,
        "lloc": 38,
        "mi": 85.14,
        "mIwoC": 49.9,
        "commentWeight": 35.24,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 6.33,
        "relativeSystemComplexity": 6.33,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 38,
        "totalSystemComplexity": 38,
        "package": "Snicco\\Component\\Session\\ValueObject\\",
        "pageRank": 0.01,
        "afferentCoupling": 9,
        "efferentCoupling": 3,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\ValueObject\\ReadOnlySession",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromSession",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boolean",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createdAt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "exists",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasOldInput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "id",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lastActivity",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lastRotation",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "missing",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "oldInput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "only",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "userId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 16,
        "nbMethods": 15,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 15,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 16,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\Session\\ImmutableSession",
            "Snicco\\Component\\Session\\Session",
            "Snicco\\Component\\Session\\ValueObject\\ReadOnlySession",
            "Snicco\\Component\\Session\\Session",
            "Snicco\\Component\\Session\\ValueObject\\ReadOnlySession",
            "Snicco\\Component\\Session\\ValueObject\\SessionId"
        ],
        "parents": [],
        "lcom": 2,
        "length": 57,
        "vocabulary": 7,
        "volume": 160.02,
        "difficulty": 8.2,
        "effort": 1312.16,
        "level": 0.12,
        "bugs": 0.05,
        "time": 73,
        "intelligentContent": 19.51,
        "number_operators": 16,
        "number_operands": 41,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 69,
        "lloc": 69,
        "mi": 44.32,
        "mIwoC": 44.32,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 1.05,
        "relativeSystemComplexity": 197.05,
        "totalStructuralComplexity": 3136,
        "totalDataComplexity": 16.87,
        "totalSystemComplexity": 3152.87,
        "package": "Snicco\\Component\\Session\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 5,
        "instability": 0.63,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\ValueObject\\SessionLottery",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "wins",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "LogicException",
            "LogicException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 19,
        "vocabulary": 12,
        "volume": 68.11,
        "difficulty": 4.29,
        "effort": 291.92,
        "level": 0.23,
        "bugs": 0.02,
        "time": 16,
        "intelligentContent": 15.89,
        "number_operators": 7,
        "number_operands": 12,
        "number_operators_unique": 5,
        "number_operands_unique": 7,
        "cloc": 7,
        "loc": 26,
        "lloc": 19,
        "mi": 94.87,
        "mIwoC": 58.87,
        "commentWeight": 36,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "Snicco\\Component\\Session\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\ValueObject\\CookiePool",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromSuperGlobals",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 5,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\Session\\ValueObject\\CookiePool",
            "Snicco\\Component\\Session\\ValueObject\\CookiePool"
        ],
        "parents": [],
        "lcom": 2,
        "length": 15,
        "vocabulary": 7,
        "volume": 42.11,
        "difficulty": 3.75,
        "effort": 157.91,
        "level": 0.27,
        "bugs": 0.01,
        "time": 9,
        "intelligentContent": 11.23,
        "number_operators": 5,
        "number_operands": 10,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 17,
        "loc": 38,
        "lloc": 21,
        "mi": 102.54,
        "mIwoC": 59.51,
        "commentWeight": 43.02,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.75,
        "relativeSystemComplexity": 3.75,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 15,
        "totalSystemComplexity": 15,
        "package": "Snicco\\Component\\Session\\ValueObject\\",
        "pageRank": 0.09,
        "afferentCoupling": 5,
        "efferentCoupling": 2,
        "instability": 0.29,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\ValueObject\\SessionCookie",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "value",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "name",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sameSite",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "path",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "domain",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "secureOnly",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "httpOnly",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "expiryTimestamp",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lifetime",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 8,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 57,
        "vocabulary": 16,
        "volume": 228,
        "difficulty": 6.17,
        "effort": 1406,
        "level": 0.16,
        "bugs": 0.08,
        "time": 78,
        "intelligentContent": 36.97,
        "number_operators": 20,
        "number_operands": 37,
        "number_operators_unique": 4,
        "number_operands_unique": 12,
        "cloc": 6,
        "loc": 68,
        "lloc": 62,
        "mi": 66.33,
        "mIwoC": 44.12,
        "commentWeight": 22.21,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 10.8,
        "relativeSystemComplexity": 10.8,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 108,
        "totalSystemComplexity": 108,
        "package": "Snicco\\Component\\Session\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Event\\SessionRotated",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\Session\\ImmutableSession"
        ],
        "parents": [],
        "lcom": 1,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 0.75,
        "effort": 4.75,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 8.45,
        "number_operators": 1,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 9,
        "lloc": 9,
        "mi": 73.43,
        "mIwoC": 73.43,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "Snicco\\Component\\Session\\Event\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\ReadWriteSession",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createEmpty",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "put",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boolean",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createdAt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "decrement",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "increment",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "flashInput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "flash",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "push",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasOldInput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "oldInput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "id",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "invalidate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rotate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "flush",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "keep",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lastActivity",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lastRotation",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "flashNow",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "only",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "putIfMissing",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "missing",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "exists",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "reflash",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "releaseEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remove",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "replace",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveUsing",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "forget",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUserId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "userId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isDirty",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "checkLocked",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeFromOldFlashData",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "oldFlashes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "recordEvent",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "mergeNewFlashes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "ageFlashData",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lock",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 43,
        "nbMethods": 41,
        "nbMethodsPrivate": 7,
        "nbMethodsPublic": 34,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 73,
        "ccn": 31,
        "ccnMethodMax": 4,
        "externals": [
            "Snicco\\Component\\Session\\Session",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ReadWriteSession",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\StrArr\\Arr",
            "RuntimeException",
            "LogicException",
            "LogicException",
            "RuntimeException",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ValueObject\\ReadOnlySession",
            "Snicco\\Component\\Session\\Event\\SessionRotated",
            "RuntimeException",
            "Snicco\\Component\\StrArr\\Arr",
            "Closure",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\Session\\Driver\\SessionDriver",
            "Snicco\\Component\\Session\\Serializer\\Serializer",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\StrArr\\Arr",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "Snicco\\Component\\Session\\Exception\\SessionIsLocked",
            "Snicco\\Component\\StrArr\\Arr",
            "RuntimeException",
            "RuntimeException"
        ],
        "parents": [],
        "lcom": 2,
        "length": 393,
        "vocabulary": 62,
        "volume": 2340,
        "difficulty": 29.52,
        "effort": 69074.97,
        "level": 0.03,
        "bugs": 0.78,
        "time": 3837,
        "intelligentContent": 79.27,
        "number_operators": 86,
        "number_operands": 307,
        "number_operators_unique": 10,
        "number_operands_unique": 52,
        "cloc": 48,
        "loc": 343,
        "lloc": 295,
        "mi": 45.74,
        "mIwoC": 18.36,
        "commentWeight": 27.38,
        "kanDefect": 2.08,
        "relativeStructuralComplexity": 841,
        "relativeDataComplexity": 0.77,
        "relativeSystemComplexity": 841.77,
        "totalStructuralComplexity": 36163,
        "totalDataComplexity": 32.97,
        "totalSystemComplexity": 36195.97,
        "package": "Snicco\\Component\\Session\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 15,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Driver\\EncryptedDriver",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "gc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "read",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "touch",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "write",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroyAll",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroyAllForUserId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroyAllForUserIdExcept",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllForUserId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 10,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 10,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 5,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\Session\\Driver\\UserSessionsDriver",
            "Snicco\\Component\\Session\\Driver\\SessionDriver",
            "Snicco\\Component\\Session\\SessionEncryptor",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "BadMethodCallException",
            "BadMethodCallException",
            "BadMethodCallException",
            "BadMethodCallException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 82,
        "vocabulary": 18,
        "volume": 341.93,
        "difficulty": 9,
        "effort": 3077.4,
        "level": 0.11,
        "bugs": 0.11,
        "time": 171,
        "intelligentContent": 37.99,
        "number_operators": 19,
        "number_operands": 63,
        "number_operators_unique": 4,
        "number_operands_unique": 14,
        "cloc": 0,
        "loc": 62,
        "lloc": 62,
        "mi": 42.49,
        "mIwoC": 42.49,
        "commentWeight": 0,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 256,
        "relativeDataComplexity": 0.19,
        "relativeSystemComplexity": 256.19,
        "totalStructuralComplexity": 2560,
        "totalDataComplexity": 1.94,
        "totalSystemComplexity": 2561.94,
        "package": "Snicco\\Component\\Session\\Driver\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Driver\\InMemoryDriver",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "gc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "read",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "touch",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "write",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroyAll",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroyAllForUserId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroyAllForUserIdExcept",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllForUserId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calculateExpiration",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 11,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 10,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 26,
        "ccn": 15,
        "ccnMethodMax": 4,
        "externals": [
            "Snicco\\Component\\Session\\Driver\\UserSessionsDriver",
            "Snicco\\Component\\TestableClock\\Clock",
            "Snicco\\Component\\TestableClock\\SystemClock",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\Session\\Exception\\BadSessionID",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession",
            "Snicco\\Component\\Session\\Exception\\BadSessionID",
            "Snicco\\Component\\Session\\ValueObject\\SerializedSession"
        ],
        "parents": [],
        "lcom": 1,
        "length": 126,
        "vocabulary": 27,
        "volume": 599.12,
        "difficulty": 25,
        "effort": 14977.9,
        "level": 0.04,
        "bugs": 0.2,
        "time": 832,
        "intelligentContent": 23.96,
        "number_operators": 26,
        "number_operands": 100,
        "number_operators_unique": 9,
        "number_operands_unique": 18,
        "cloc": 3,
        "loc": 86,
        "lloc": 83,
        "mi": 50.94,
        "mIwoC": 36.67,
        "commentWeight": 14.27,
        "kanDefect": 1.79,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.46,
        "relativeSystemComplexity": 100.46,
        "totalStructuralComplexity": 1200,
        "totalDataComplexity": 5.55,
        "totalSystemComplexity": 1205.55,
        "package": "Snicco\\Component\\Session\\Driver\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Exception\\SessionIsLocked",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "LogicException",
            "Throwable"
        ],
        "parents": [
            "LogicException"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 5,
        "volume": 18.58,
        "difficulty": 0,
        "effort": 0,
        "level": 1.25,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 8,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 71.28,
        "mIwoC": 71.28,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 2.5,
        "package": "Snicco\\Component\\Session\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Exception\\BadSessionID",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "forSelector",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "InvalidArgumentException",
            "Snicco\\Component\\Session\\Exception\\BadSessionID"
        ],
        "parents": [
            "InvalidArgumentException"
        ],
        "lcom": 1,
        "length": 9,
        "vocabulary": 7,
        "volume": 25.27,
        "difficulty": 0.67,
        "effort": 16.84,
        "level": 1.5,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 37.9,
        "number_operators": 1,
        "number_operands": 8,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 70.34,
        "mIwoC": 70.34,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "Snicco\\Component\\Session\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 4,
        "efferentCoupling": 3,
        "instability": 0.43,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Exception\\CouldNotReadSessionContent",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "forID",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "RuntimeException",
            "Snicco\\Component\\Session\\Exception\\CouldNotReadSessionContent",
            "Snicco\\Component\\Session\\Exception\\CouldNotReadSessionContent"
        ],
        "parents": [
            "RuntimeException"
        ],
        "lcom": 1,
        "length": 14,
        "vocabulary": 9,
        "volume": 44.38,
        "difficulty": 0.81,
        "effort": 36.06,
        "level": 1.23,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 54.62,
        "number_operators": 1,
        "number_operands": 13,
        "number_operators_unique": 1,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 68.5,
        "mIwoC": 68.5,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 3,
        "package": "Snicco\\Component\\Session\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 3,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Exception\\CouldNotDestroySessions",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "forSessionIDs",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "RuntimeException",
            "Snicco\\Component\\Session\\Exception\\CouldNotDestroySessions",
            "Throwable"
        ],
        "parents": [
            "RuntimeException"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 7,
        "volume": 33.69,
        "difficulty": 0.92,
        "effort": 30.88,
        "level": 1.09,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 36.75,
        "number_operators": 1,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 105.52,
        "mIwoC": 69.34,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 3,
        "package": "Snicco\\Component\\Session\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 4,
        "instability": 0.57,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Exception\\CouldNotWriteSessionContent",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "forId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "RuntimeException",
            "Snicco\\Component\\Session\\Exception\\CouldNotWriteSessionContent",
            "Throwable"
        ],
        "parents": [
            "RuntimeException"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 9,
        "volume": 38.04,
        "difficulty": 0.69,
        "effort": 26.15,
        "level": 1.45,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 55.33,
        "number_operators": 1,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 69.1,
        "mIwoC": 69.1,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "package": "Snicco\\Component\\Session\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 4,
        "instability": 0.57,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\SessionManager\\FactorySessionManager",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "start",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toCookie",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "gc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parseSessionId",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadSessionFromDriver",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isIdle",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "needsRotation",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isExpired",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hash",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 11,
        "nbMethodsPrivate": 6,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 23,
        "ccn": 13,
        "ccnMethodMax": 4,
        "externals": [
            "Snicco\\Component\\Session\\SessionManager\\SessionManager",
            "Snicco\\Component\\Session\\ValueObject\\SessionConfig",
            "Snicco\\Component\\Session\\Driver\\SessionDriver",
            "Snicco\\Component\\Session\\Serializer\\Serializer",
            "Snicco\\Component\\TestableClock\\SystemClock",
            "Snicco\\Component\\Session\\EventDispatcher\\NullSessionDispatcher",
            "Snicco\\Component\\Session\\Session",
            "Snicco\\Component\\Session\\ValueObject\\CookiePool",
            "Snicco\\Component\\Session\\Session",
            "Snicco\\Component\\Session\\ValueObject\\SessionCookie",
            "Snicco\\Component\\Session\\ImmutableSession",
            "Snicco\\Component\\Session\\ValueObject\\SessionCookie",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ValueObject\\CookiePool",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "Snicco\\Component\\Session\\ReadWriteSession",
            "Snicco\\Component\\Session\\ValueObject\\SessionId",
            "RuntimeException",
            "Snicco\\Component\\Session\\ReadWriteSession",
            "Snicco\\Component\\Session\\ReadWriteSession",
            "Snicco\\Component\\Session\\Session",
            "Snicco\\Component\\Session\\Session",
            "Snicco\\Component\\Session\\Session",
            "RuntimeException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 163,
        "vocabulary": 35,
        "volume": 836.07,
        "difficulty": 17.33,
        "effort": 14491.93,
        "level": 0.06,
        "bugs": 0.28,
        "time": 805,
        "intelligentContent": 48.23,
        "number_operators": 46,
        "number_operands": 117,
        "number_operators_unique": 8,
        "number_operands_unique": 27,
        "cloc": 8,
        "loc": 108,
        "lloc": 100,
        "mi": 54.62,
        "mIwoC": 34.16,
        "commentWeight": 20.46,
        "kanDefect": 0.64,
        "relativeStructuralComplexity": 1600,
        "relativeDataComplexity": 0.27,
        "relativeSystemComplexity": 1600.27,
        "totalStructuralComplexity": 17600,
        "totalDataComplexity": 3.02,
        "totalSystemComplexity": 17603.02,
        "package": "Snicco\\Component\\Session\\SessionManager\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 13,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\SessionManager\\SingleSessionSessionManager",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "start",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toCookie",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "gc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 6,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\Session\\SessionManager\\SessionManager",
            "Snicco\\Component\\Session\\SessionManager\\SessionManager",
            "Snicco\\Component\\Session\\Session",
            "Snicco\\Component\\Session\\ValueObject\\CookiePool",
            "Snicco\\Component\\Session\\Session",
            "Snicco\\Component\\Session\\ValueObject\\SessionCookie",
            "Snicco\\Component\\Session\\ImmutableSession"
        ],
        "parents": [],
        "lcom": 1,
        "length": 21,
        "vocabulary": 7,
        "volume": 58.95,
        "difficulty": 6,
        "effort": 353.73,
        "level": 0.17,
        "bugs": 0.02,
        "time": 20,
        "intelligentContent": 9.83,
        "number_operators": 5,
        "number_operands": 16,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 4,
        "loc": 33,
        "lloc": 29,
        "mi": 81.11,
        "mIwoC": 55.43,
        "commentWeight": 25.68,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.56,
        "relativeSystemComplexity": 16.56,
        "totalStructuralComplexity": 80,
        "totalDataComplexity": 2.8,
        "totalSystemComplexity": 82.8,
        "package": "Snicco\\Component\\Session\\SessionManager\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Serializer\\PHPSerializer",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "serialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deserialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\Session\\Serializer\\Serializer",
            "RuntimeException",
            "RuntimeException"
        ],
        "parents": [],
        "lcom": 2,
        "length": 22,
        "vocabulary": 13,
        "volume": 81.41,
        "difficulty": 3.33,
        "effort": 271.37,
        "level": 0.3,
        "bugs": 0.03,
        "time": 15,
        "intelligentContent": 24.42,
        "number_operators": 7,
        "number_operands": 15,
        "number_operators_unique": 4,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 20,
        "lloc": 20,
        "mi": 57.97,
        "mIwoC": 57.97,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 6,
        "package": "Snicco\\Component\\Session\\Serializer\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\Serializer\\JsonSerializer",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "serialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deserialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\Session\\Serializer\\Serializer"
        ],
        "parents": [],
        "lcom": 2,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 1.75,
        "effort": 45.24,
        "level": 0.57,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 14.77,
        "number_operators": 3,
        "number_operands": 7,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 1,
        "loc": 14,
        "lloc": 13,
        "mi": 85.79,
        "mIwoC": 65.68,
        "commentWeight": 20.12,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 6,
        "package": "Snicco\\Component\\Session\\Serializer\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Session\\EventDispatcher\\NullSessionDispatcher",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "dispatchAll",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\Session\\EventDispatcher\\SessionEventDispatcher"
        ],
        "parents": [],
        "lcom": 1,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 1,
        "loc": 8,
        "lloc": 7,
        "mi": 197.04,
        "mIwoC": 171,
        "commentWeight": 26.04,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "Snicco\\Component\\Session\\EventDispatcher\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    }
]