var classes = [
    {
        "name": "Snicco\\Component\\Kernel\\Testing\\DIContainerContractTest",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "createContainer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_factory_returns_different_objects",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_singleton_returns_the_same_object",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_instance_returns_the_same_object",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "services_can_be_redefined",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_primitive",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_primitive_throws_for_non_scalar_array",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_overwritten_frozen_services_throws_exception",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_overwritten_primitive_throws_exception",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_lock_throws_exception_for_singleton",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_lock_throws_exception_for_factory",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_lock_throws_exception_for_instance",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_lock_throws_for_primitive",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_lock_throws_exception_for_array_set",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_lock_throws_exception_for_array_unset",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_make_returns_the_correct_class_instance",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_make_throws_exception_if_class_string_id_does_not_return_class",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_offsetGet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_offsetSet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_offsetUnset",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_offsetExists",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "test_has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 22,
        "nbMethods": 22,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 22,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 26,
        "ccn": 5,
        "ccnMethodMax": 4,
        "externals": [
            "Snicco\\Component\\Kernel\\DIContainer",
            "Snicco\\Component\\Kernel\\Testing\\Foo",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\Kernel\\Testing\\Foo",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\Kernel\\Testing\\Foo",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\Kernel\\Testing\\Foo",
            "Snicco\\Component\\Kernel\\Testing\\Bar",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "stdClass",
            "PHPUnit\\Framework\\Assert",
            "stdClass",
            "Snicco\\Component\\Kernel\\Testing\\Foo",
            "Snicco\\Component\\Kernel\\Testing\\Bar",
            "Snicco\\Component\\Kernel\\Testing\\Foo",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\Kernel\\Testing\\Foo",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\Kernel\\Testing\\Bar",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\Kernel\\Testing\\Bar",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\Kernel\\Testing\\Bar",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\Kernel\\Testing\\Foo",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "stdClass",
            "Snicco\\Component\\Kernel\\Testing\\Foo",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\Kernel\\Testing\\Foo",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\Kernel\\Testing\\Foo",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "Snicco\\Component\\Kernel\\Testing\\Bar",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert",
            "PHPUnit\\Framework\\Assert"
        ],
        "parents": [],
        "lcom": 1,
        "length": 354,
        "vocabulary": 33,
        "volume": 1785.72,
        "difficulty": 14.35,
        "effort": 25625.02,
        "level": 0.07,
        "bugs": 0.6,
        "time": 1424,
        "intelligentContent": 124.44,
        "number_operators": 67,
        "number_operands": 287,
        "number_operators_unique": 3,
        "number_operands_unique": 30,
        "cloc": 76,
        "loc": 323,
        "lloc": 247,
        "mi": 58.5,
        "mIwoC": 24.36,
        "commentWeight": 34.14,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.77,
        "relativeSystemComplexity": 144.77,
        "totalStructuralComplexity": 3168,
        "totalDataComplexity": 16.92,
        "totalSystemComplexity": 3184.92,
        "package": "Snicco\\Component\\Kernel\\Testing\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Kernel\\Testing\\Foo",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Snicco\\Component\\Kernel\\Testing\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Kernel\\Testing\\Bar",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Snicco\\Component\\Kernel\\Testing\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Kernel\\ValueObject\\Environment",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isProduction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "prod",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testing",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dev",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "staging",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "asString",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isDevelop",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isTesting",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isStaging",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isDebug",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isCli",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validEnvironments",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 14,
        "nbMethods": 12,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 10,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 18,
        "ccn": 5,
        "ccnMethodMax": 4,
        "externals": [
            "Webmozart\\Assert\\Assert",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "Snicco\\Component\\Kernel\\ValueObject\\Environment",
            "Snicco\\Component\\Kernel\\ValueObject\\Environment",
            "Snicco\\Component\\Kernel\\ValueObject\\Environment",
            "Snicco\\Component\\Kernel\\ValueObject\\Environment"
        ],
        "parents": [],
        "lcom": 7,
        "length": 65,
        "vocabulary": 21,
        "volume": 285.5,
        "difficulty": 8,
        "effort": 2284.01,
        "level": 0.13,
        "bugs": 0.1,
        "time": 127,
        "intelligentContent": 35.69,
        "number_operators": 25,
        "number_operands": 40,
        "number_operators_unique": 6,
        "number_operands_unique": 15,
        "cloc": 15,
        "loc": 90,
        "lloc": 75,
        "mi": 70.79,
        "mIwoC": 41.23,
        "commentWeight": 29.56,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 3.38,
        "relativeSystemComplexity": 12.38,
        "totalStructuralComplexity": 126,
        "totalDataComplexity": 47.25,
        "totalSystemComplexity": 173.25,
        "package": "Snicco\\Component\\Kernel\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 15,
        "efferentCoupling": 4,
        "instability": 0.21,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Kernel\\ValueObject\\Directories",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromDefaults",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configDir",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "baseDir",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cacheDir",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logDir",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 4,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert",
            "Snicco\\Component\\Kernel\\ValueObject\\Directories"
        ],
        "parents": [],
        "lcom": 2,
        "length": 72,
        "vocabulary": 18,
        "volume": 300.23,
        "difficulty": 5,
        "effort": 1501.17,
        "level": 0.2,
        "bugs": 0.1,
        "time": 83,
        "intelligentContent": 60.05,
        "number_operators": 22,
        "number_operands": 50,
        "number_operators_unique": 3,
        "number_operands_unique": 15,
        "cloc": 7,
        "loc": 51,
        "lloc": 44,
        "mi": 73.82,
        "mIwoC": 46.67,
        "commentWeight": 27.15,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.92,
        "relativeSystemComplexity": 3.92,
        "totalStructuralComplexity": 6,
        "totalDataComplexity": 17.5,
        "totalSystemComplexity": 23.5,
        "package": "Snicco\\Component\\Kernel\\ValueObject\\",
        "pageRank": 0,
        "afferentCoupling": 5,
        "efferentCoupling": 3,
        "instability": 0.38,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Kernel\\Kernel",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "env",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "container",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "directories",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "config",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "usesBundle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "afterRegister",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "afterConfigurationLoaded",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadConfiguration",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "registerBundles",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bootBundles",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configCacheFile",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bundlesInCurrentEnv",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addBundle",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bootstrappersInCurrentEnv",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addBootstrapper",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setBundlesAndBootstrappers",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "determineCache",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 19,
        "nbMethods": 16,
        "nbMethodsPrivate": 10,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "wmc": 47,
        "ccn": 29,
        "ccnMethodMax": 7,
        "externals": [
            "Snicco\\Component\\Kernel\\DIContainer",
            "Snicco\\Component\\Kernel\\ValueObject\\Environment",
            "Snicco\\Component\\Kernel\\ValueObject\\Directories",
            "LogicException",
            "Snicco\\Component\\Kernel\\Configuration\\ReadOnlyConfig",
            "Snicco\\Component\\Kernel\\ValueObject\\Environment",
            "Snicco\\Component\\Kernel\\DIContainer",
            "Snicco\\Component\\Kernel\\ValueObject\\Directories",
            "Snicco\\Component\\Kernel\\Configuration\\ReadOnlyConfig",
            "LogicException",
            "LogicException",
            "LogicException",
            "Snicco\\Component\\Kernel\\Configuration\\ConfigLoader",
            "Snicco\\Component\\Kernel\\Configuration\\WritableConfig",
            "InvalidArgumentException",
            "Generator",
            "bundle",
            "Snicco\\Component\\Kernel\\Bundle",
            "RuntimeException",
            "Generator",
            "class",
            "Snicco\\Component\\Kernel\\Bootstrapper",
            "Snicco\\Component\\Kernel\\Configuration\\ConfigCache",
            "Snicco\\Component\\Kernel\\ValueObject\\Environment",
            "Snicco\\Component\\Kernel\\Configuration\\PHPFileCache",
            "Snicco\\Component\\Kernel\\Configuration\\NullCache"
        ],
        "parents": [],
        "lcom": 1,
        "length": 222,
        "vocabulary": 38,
        "volume": 1165.04,
        "difficulty": 16.22,
        "effort": 18895.49,
        "level": 0.06,
        "bugs": 0.39,
        "time": 1050,
        "intelligentContent": 71.83,
        "number_operators": 49,
        "number_operands": 173,
        "number_operators_unique": 6,
        "number_operands_unique": 32,
        "cloc": 35,
        "loc": 212,
        "lloc": 177,
        "mi": 55.03,
        "mIwoC": 25.59,
        "commentWeight": 29.44,
        "kanDefect": 3.75,
        "relativeStructuralComplexity": 841,
        "relativeDataComplexity": 0.39,
        "relativeSystemComplexity": 841.39,
        "totalStructuralComplexity": 15979,
        "totalDataComplexity": 7.43,
        "totalSystemComplexity": 15986.43,
        "package": "Snicco\\Component\\Kernel\\",
        "pageRank": 0,
        "afferentCoupling": 13,
        "efferentCoupling": 17,
        "instability": 0.57,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Kernel\\DIContainer",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "lock",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "factory",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "offsetGet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "offsetSet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "make",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "singleton",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "instance",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "primitive",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 7,
        "ccnMethodMax": 4,
        "externals": [
            "ArrayAccess",
            "Psr\\Container\\ContainerInterface",
            "Closure",
            "LogicException",
            "Closure",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert"
        ],
        "parents": [],
        "lcom": 4,
        "length": 69,
        "vocabulary": 16,
        "volume": 276,
        "difficulty": 9.33,
        "effort": 2576,
        "level": 0.11,
        "bugs": 0.09,
        "time": 143,
        "intelligentContent": 29.57,
        "number_operators": 13,
        "number_operands": 56,
        "number_operators_unique": 4,
        "number_operands_unique": 12,
        "cloc": 89,
        "loc": 137,
        "lloc": 48,
        "mi": 92.72,
        "mIwoC": 45.29,
        "commentWeight": 47.43,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 1.07,
        "relativeSystemComplexity": 37.07,
        "totalStructuralComplexity": 288,
        "totalDataComplexity": 8.57,
        "totalSystemComplexity": 296.57,
        "package": "Snicco\\Component\\Kernel\\",
        "pageRank": 0,
        "afferentCoupling": 7,
        "efferentCoupling": 5,
        "instability": 0.42,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Kernel\\Exception\\ContainerIsLocked",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "whileSettingId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "whileRemovingId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "RuntimeException",
            "Psr\\Container\\ContainerExceptionInterface",
            "Snicco\\Component\\Kernel\\Exception\\ContainerIsLocked",
            "Snicco\\Component\\Kernel\\Exception\\ContainerIsLocked"
        ],
        "parents": [
            "RuntimeException"
        ],
        "lcom": 2,
        "length": 12,
        "vocabulary": 7,
        "volume": 33.69,
        "difficulty": 0.83,
        "effort": 28.07,
        "level": 1.2,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 40.43,
        "number_operators": 2,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 12,
        "lloc": 12,
        "mi": 65.63,
        "mIwoC": 65.63,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 6,
        "package": "Snicco\\Component\\Kernel\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 4,
        "efferentCoupling": 4,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Kernel\\Exception\\FrozenService",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "forId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "RuntimeException",
            "Psr\\Container\\ContainerExceptionInterface",
            "Snicco\\Component\\Kernel\\Exception\\FrozenService"
        ],
        "parents": [
            "RuntimeException"
        ],
        "lcom": 1,
        "length": 6,
        "vocabulary": 5,
        "volume": 13.93,
        "difficulty": 0.63,
        "effort": 8.71,
        "level": 1.6,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 22.29,
        "number_operators": 1,
        "number_operands": 5,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 72.16,
        "mIwoC": 72.16,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "Snicco\\Component\\Kernel\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 4,
        "efferentCoupling": 4,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Kernel\\Exception\\MissingConfigKey",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "RuntimeException"
        ],
        "parents": [
            "RuntimeException"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Snicco\\Component\\Kernel\\Exception\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Kernel\\Configuration\\NullCache",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Snicco\\Component\\Kernel\\Configuration\\ConfigCache"
        ],
        "parents": [],
        "lcom": 1,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 0.75,
        "effort": 4.75,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 8.45,
        "number_operators": 1,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 74.55,
        "mIwoC": 74.55,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "Snicco\\Component\\Kernel\\Configuration\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Kernel\\Configuration\\Config",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getInteger",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBoolean",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getListOfStrings",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert"
        ],
        "parents": [],
        "lcom": 1,
        "length": 77,
        "vocabulary": 15,
        "volume": 300.83,
        "difficulty": 5.15,
        "effort": 1550.43,
        "level": 0.19,
        "bugs": 0.1,
        "time": 86,
        "intelligentContent": 58.37,
        "number_operators": 10,
        "number_operands": 67,
        "number_operators_unique": 2,
        "number_operands_unique": 13,
        "cloc": 9,
        "loc": 45,
        "lloc": 36,
        "mi": 80.5,
        "mIwoC": 48.56,
        "commentWeight": 31.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 2.33,
        "relativeSystemComplexity": 6.33,
        "totalStructuralComplexity": 24,
        "totalDataComplexity": 14,
        "totalSystemComplexity": 38,
        "package": "Snicco\\Component\\Kernel\\Configuration\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Kernel\\Configuration\\PHPFileCache",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "read",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\Kernel\\Configuration\\ConfigCache",
            "Webimpress\\SafeWriter\\FileWriter"
        ],
        "parents": [],
        "lcom": 1,
        "length": 35,
        "vocabulary": 14,
        "volume": 133.26,
        "difficulty": 6.11,
        "effort": 814.35,
        "level": 0.16,
        "bugs": 0.04,
        "time": 45,
        "intelligentContent": 21.81,
        "number_operators": 13,
        "number_operands": 22,
        "number_operators_unique": 5,
        "number_operands_unique": 9,
        "cloc": 2,
        "loc": 32,
        "lloc": 30,
        "mi": 71.38,
        "mIwoC": 52.5,
        "commentWeight": 18.88,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.67,
        "relativeSystemComplexity": 5.67,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 17,
        "package": "Snicco\\Component\\Kernel\\Configuration\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Kernel\\Configuration\\ConfigLoader",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findConfigFiles",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 7,
        "ccnMethodMax": 5,
        "externals": [
            "InvalidArgumentException",
            "FilesystemIterator"
        ],
        "parents": [],
        "lcom": 1,
        "length": 48,
        "vocabulary": 20,
        "volume": 207.45,
        "difficulty": 5.67,
        "effort": 1175.56,
        "level": 0.18,
        "bugs": 0.07,
        "time": 65,
        "intelligentContent": 36.61,
        "number_operators": 14,
        "number_operands": 34,
        "number_operators_unique": 5,
        "number_operands_unique": 15,
        "cloc": 12,
        "loc": 41,
        "lloc": 29,
        "mi": 88.1,
        "mIwoC": 50.93,
        "commentWeight": 37.17,
        "kanDefect": 0.75,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 25.5,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 51,
        "package": "Snicco\\Component\\Kernel\\Configuration\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Kernel\\Configuration\\WritableConfig",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "extend",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "append",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "set",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setIfMissing",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "prepend",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toArray",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "mergedArrayConfig",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isList",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 11,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 32,
        "ccn": 21,
        "ccnMethodMax": 6,
        "externals": [
            "Snicco\\Component\\Kernel\\Configuration\\Config",
            "Webmozart\\Assert\\Assert",
            "LogicException",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert",
            "Snicco\\Component\\StrArr\\Arr",
            "LogicException",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\StrArr\\Arr",
            "LogicException",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\StrArr\\Arr",
            "LogicException",
            "Snicco\\Component\\StrArr\\Arr"
        ],
        "parents": [
            "Snicco\\Component\\Kernel\\Configuration\\Config"
        ],
        "lcom": 2,
        "length": 200,
        "vocabulary": 33,
        "volume": 1008.88,
        "difficulty": 20.73,
        "effort": 20914.83,
        "level": 0.05,
        "bugs": 0.34,
        "time": 1162,
        "intelligentContent": 48.67,
        "number_operators": 46,
        "number_operands": 154,
        "number_operators_unique": 7,
        "number_operands_unique": 26,
        "cloc": 40,
        "loc": 146,
        "lloc": 106,
        "mi": 68.21,
        "mIwoC": 31.96,
        "commentWeight": 36.24,
        "kanDefect": 1.54,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 1.44,
        "relativeSystemComplexity": 50.44,
        "totalStructuralComplexity": 588,
        "totalDataComplexity": 17.25,
        "totalSystemComplexity": 605.25,
        "package": "Snicco\\Component\\Kernel\\Configuration\\",
        "pageRank": 0,
        "afferentCoupling": 12,
        "efferentCoupling": 4,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "Snicco\\Component\\Kernel\\Configuration\\ReadOnlyConfig",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toArray",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 1,
        "wmc": 5,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Snicco\\Component\\Kernel\\Configuration\\Config",
            "Snicco\\Component\\StrArr\\Arr",
            "Snicco\\Component\\Kernel\\Exception\\MissingConfigKey",
            "Snicco\\Component\\StrArr\\Arr"
        ],
        "parents": [
            "Snicco\\Component\\Kernel\\Configuration\\Config"
        ],
        "lcom": 2,
        "length": 21,
        "vocabulary": 10,
        "volume": 69.76,
        "difficulty": 3.43,
        "effort": 239.18,
        "level": 0.29,
        "bugs": 0.02,
        "time": 13,
        "intelligentContent": 20.35,
        "number_operators": 5,
        "number_operands": 16,
        "number_operators_unique": 3,
        "number_operands_unique": 7,
        "cloc": 5,
        "loc": 29,
        "lloc": 24,
        "mi": 86.7,
        "mIwoC": 56.71,
        "commentWeight": 29.99,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 12,
        "package": "Snicco\\Component\\Kernel\\Configuration\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    }
]