var classes = [
    {
        "name": "Snicco\\Middleware\\WPNonce\\WPNonce",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createNonce",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "noHtml",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Snicco\\Component\\HttpRouting\\Routing\\UrlGenerator\\UrlGenerator",
            "Snicco\\Component\\BetterWPAPI\\BetterWPAPI",
            "Snicco\\Middleware\\WPNonce\\VerifyWPNonce"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 52,
        "vocabulary": 19,
        "volume": 220.89,
        "difficulty": 8.54,
        "effort": 1886.08,
        "level": 0.12,
        "bugs": 0.07,
        "time": 105,
        "intelligentContent": 25.87,
        "number_operators": 15,
        "number_operands": 37,
        "number_operators_unique": 6,
        "number_operands_unique": 13,
        "cloc": 3,
        "loc": 39,
        "lloc": 36,
        "mi": 70.06,
        "mIwoC": 49.23,
        "commentWeight": 20.83,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.95,
        "relativeSystemComplexity": 16.95,
        "totalStructuralComplexity": 64,
        "totalDataComplexity": 3.8,
        "totalSystemComplexity": 67.8,
        "package": "Snicco\\Middleware\\WPNonce\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Snicco\\Middleware\\WPNonce\\VerifyWPNonce",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "inputKey",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 5,
        "ccnMethodMax": 4,
        "externals": [
            "Snicco\\Component\\HttpRouting\\Middleware\\Middleware",
            "Snicco\\Component\\BetterWPAPI\\BetterWPAPI",
            "Snicco\\Component\\BetterWPAPI\\BetterWPAPI",
            "Psr\\Http\\Message\\ResponseInterface",
            "Snicco\\Component\\HttpRouting\\Http\\Psr7\\Request",
            "Snicco\\Component\\HttpRouting\\Middleware\\NextMiddleware",
            "Snicco\\Middleware\\WPNonce\\WPNonce",
            "Snicco\\Component\\Psr7ErrorHandler\\HttpException"
        ],
        "parents": [
            "Snicco\\Component\\HttpRouting\\Middleware\\Middleware"
        ],
        "implements": [],
        "lcom": 2,
        "length": 46,
        "vocabulary": 18,
        "volume": 191.82,
        "difficulty": 4.71,
        "effort": 904.28,
        "level": 0.21,
        "bugs": 0.06,
        "time": 50,
        "intelligentContent": 40.69,
        "number_operators": 13,
        "number_operands": 33,
        "number_operators_unique": 4,
        "number_operands_unique": 14,
        "cloc": 0,
        "loc": 30,
        "lloc": 30,
        "mi": 51.12,
        "mIwoC": 51.12,
        "commentWeight": 0,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.63,
        "relativeSystemComplexity": 49.63,
        "totalStructuralComplexity": 147,
        "totalDataComplexity": 1.88,
        "totalSystemComplexity": 148.88,
        "package": "Snicco\\Middleware\\WPNonce\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 7,
        "instability": 0.88,
        "violations": {}
    }
]