name: 'Conventional PR'

on:
  # See https://github.com/amannn/action-semantic-pull-request#event-triggers for why pull_request is not correct here.
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint_pr_title:
    name: Lint PR title
    runs-on: ubuntu-latest
    steps:
      # v4.2.0
      - uses: amannn/action-semantic-pull-request@c05e3587cb7878ec080300180d31d61ba1cf01ea
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            ci
            docs
            feat
            fix
            perf
            refactor
            style
            revert
            test
            chore
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true