name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v1

      - name: Install npm dependencies
        run: npm install

      - name: Import GPG keys
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true
          git-config-global: true

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GIT_AUTHOR_NAME: sniccowp-bot
          GIT_AUTHOR_EMAIL: sniccowp-github@snicco.de
          GIT_COMMITTER_NAME: sniccowp-bot
          GIT_COMMITTER_EMAIL: sniccowp-github@snicco.de
        run: |
          chmod +x ./bin/prepare-composer.sh
          npx semantic-release
        shell: bash