name: 'Release'
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - beta

jobs:
  release:
    name: 'Release'
    # don't run on forks
    if: github.repository == 'snicco/snicco'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # If we use the default token the snicco-bot is authenticated correctly for some reason.
          # Commits will then fail due to branch protection rules.
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Store pushed branch in env
        run: |
          PUSHED_BRANCH=${GITHUB_REF#refs/heads/}
          echo "PUSHED_BRANCH=${PUSHED_BRANCH}" >> $GITHUB_ENV
          echo "Pushed branch is $PUSHED_BRANCH"

      - name: 'Setup Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: 'Install composer dependencies'
        uses: ramsey/composer-install@v1

      - name: 'Install npm dependencies'
        run: npm install

      - name: 'Import GPG keys'
        # https://github.com/crazy-max/ghaction-import-gpg/releases/tag/v4.3.0
        uses: crazy-max/ghaction-import-gpg@4d58d49bfefed583addec96996588e8bc4b306b8
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true

      - name: 'Disable admin enforcement'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            result = github.rest.repos.deleteAdminBranchProtection({
              owner: 'snicco',
              repo: 'snicco',
              branch: '${{ env.PUSHED_BRANCH }}'
            })

      - name: 'Semantic release'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GIT_AUTHOR_NAME: snicco-bot
          GIT_AUTHOR_EMAIL: github-bot@snicco.io
          GIT_COMMITTER_NAME: snicco-bot
          GIT_COMMITTER_EMAIL: github-bot@snicco.io
        # This needs to be executable before the release.
        run: |
          chmod +x ./bin/prepare-composer.sh
          npx semantic-release
        shell: bash

      - name: 'Re-enable admin enforcement'
        uses: actions/github-script@v6
        if: always()
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            result = github.rest.repos.setAdminBranchProtection({
              owner: 'snicco',
              repo: 'snicco',
              branch: '${{ env.PUSHED_BRANCH }}'
            })